### ISSUE TITLE
Sonatype Nexus Repository Issue Tracker is moving

### ISSUE THREAD

**Issue by nblair** [sonatype/nexus-public#105]
At the end of May 2023, Sonatype will be closing access to our Jira instance at https://issues.sonatype.org/browse/NEXUS. 
That instance of Jira has been licensed for Jira Server, a product that is reaching [end-of-life with Atlassian on Feb 15, 2024](https://www.atlassian.com/migration/assess/journey-to-cloud). We expect to complete our internal Issue Tracking transition by the end of May 2023.

As a result, Sonatype will be moving our Issue Tracker for OSS installs of [Sonatype Nexus Repository](https://www.sonatype.com/products/sonatype-nexus-oss-download) within Github Issues in https://github.com/sonatype/nexus-public as of today, May 1 2023.

Pro customers can continue to use https://support.sonatype.com/. Our support platform will provide continuity for visibility into support tickets that result in internal issues.

If you are a subscriber on an issue in our old Jira instance, expect to see communication pointing here as issues will be closing in the days up to the end of the service.

**Comment by RuanXinyu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by nblair** [comment]
The first notice on impacted tickets in the  https://issues.sonatype.org/browse/NEXUS project was just sent this afternoon. We expect to send an additional notification next week.

Access to https://issues.sonatype.org/browse/NEXUS will be closing on Tuesday, May 23, 2023.

**Comment by kriegaex** [comment]
@nblair, I received notifications for 3 Jira issues I am watching, but the important information @OmarHawk also requested is missing from there. I think it is super important to explicitly mention whether existing issues will be migrated to GitHub or not. I very much hope that the answer is yes, because anything less would be an affront to users anxiously waiting for longstanding bugfixes that have been ignored by far too long already.

**Comment by nblair** [comment]
@OmarHawk we will not be migrating existing open tickets. I would kindly ask that if you are continuing to experience an issue specifically with Sonatype Nexus Repository OSS, you re-open it here. We do have a set of questions lined up in the new issue template to help us better understand each issue.

@kriegaex it is true that the issue tracker for OSSRH and Maven Central is in the same Jira instance. Those two projects are unaffected by the change occurring on May 23, 2023. They will be moving in the future to a new home prior to February 2024, but the plans are not finalized yet. Another team with Sonatype is working on that transition and will broadcast their plans as they become available.

Definitely appreciate the questions here and happy to help make this as smooth a transition as possible.

**Comment by kriegaex** [comment]
Sorry to hijack this issue, but now I am even more confused. I received e-mail notifications about 3 NEXUS issues I subscribed to, mentioning that the Jira instance will be closed by the end of this month. Specifically, the issues are all about _nexus-staging-maven-plugin_, which is used for releasing stuff to Maven Central and which still has unsolved problems with JDK 16+. So where will I be able to track those issues?

In general, like I said, not migrating the existing issues would be an affront to everyone involved. Information, time and work put into documenting and discussing the issues would be lost. Why anyone would do that, is incomprehensible to me. Sorry for my harsh wording, but this is outrageous. I do not mean to shoot the messenger, so I am not blaming you personally, @nblair.

**Comment by ite-klass** [comment]
> we will not be migrating existing open tickets
> happy to help make this as smooth a transition as possible

With all existing data being discarded, with such a hard break, I don't see how anything could be made anything I'd call smooth. The only thing one can do is general information about that fact and how to handle it.

Does *close Jira* mean archived (static website?) or disappear?

Could you elaborate your thought process driving the decision to not migrate issues? I think openly communicating your considerations and accepted downsides would help understanding and clarity and consequently how to handle the situation.

If I follow an open issue, would I basically have to manually, for every ticket, summarize the issue and potentially discussion on that ticket in a new ticket here?
Is this the expected workflow for users and issue followers?

**Comment by bendem** [comment]
That's quite a lot of knowledge and workarounds lost for open issues (1296 of them with years of context). It also looks like accounts have been disabled, I'm unable to login to search for the issues I voted on.

**Comment by kriegaex** [comment]
> It also looks like accounts have been disabled, I'm unable to login to search for the issues I voted on.

@bendem, I cannot confirm that. I am presently still able to log in.

**Comment by flitzie** [comment]
1. Go to Jira ticket -> Export -> Printable -> Save page as txt
2. Got to GitHub -> New Issue -> paste in text

**Comment by kriegaex** [comment]
@flitzie, thanks.

Unfortunately, Saving to TXT is not an available option in my browser. But I achieved fairly good results with this approach:
 * Jira: Export → Printable → Save as HTML
 * Using a local _Pandoc_ installation: `pandoc -t gfm -s NEXUS-26993.html -o NEXUS-26993.md`, where "gfm" means GitHub-flafoured markdown
 * Copy & paste markdown into a GitHub issue description or comment after optionally having edited the markdown document first, if you want to get rid of non-essential parts like Jira header/footer information.

@nblair, doesn't that cry for automation? 😉

**Comment by nblair** [comment]
We do appreciate all the input here - I'm glad to see we are able to connect here, it's a good sign this forum is working!

I want to dispel the myth that all of those tickets are being discarded or archived. In fact, that the opposite is true - all of the issues in the NEXUS project are being imported into our new internal issue tracker. 

When the new internal issue tracker is private, and accessible to Sonatype employees only - unfortunately the community will not be able to see any updates. 

The experience you have with our current Jira instance was made possible by a special type of license that Sonatype was able to negotiate with Atlassian long ago. That type of license is no longer offered in their cloud environments; all new deployments are licensed by user count. The number of non-Sonatype participants outnumbered Sonatype employees by a factor in the hundreds - multiplying any budget line item by that factor is just not possible for most companies, let alone a company of our size. As the new issues are migrated, all non-Sonatype participant identities will be lost, so no outbound email notifications with updates will occur. I apologize for that, and I can only ask that you please watch the [Release Notes](https://help.sonatype.com/repomanager3/product-information/release-notes) for a list of issues fixed in each product release.

It's true that some of you got comments for things like the staging plugin; that also is a side effect of us lumping "all things Nexus Repository" into the NEXUS project in Jira. We'll be handling the transitions for those projects separately in the coming weeks.

Appreciate the creativity of the engineering community here, but we'd prefer a fresh start rather than automated script imports. If you have an issue or two that you'd like to move here for visibility, please use our new issue template to get an up to date report on the problem you are experiencing. 

Our Pro customers will get a bit of an upgrade after the dust settles on our migration. By being fully private, it will enable us to leverage bi-directional integration with our support ticket management system. New tickets created there that result in escalated product development issues will get automatic updates, all through the ticket management system. We'd ask our Pro customers to use https://support.sonatype.com exclusively.

Thanks again - hoping to provide as much transparency as I can and help us navigate the transition.

**Comment by philomory** [comment]
@nblair Thank you for the explanation. It's not *pleasant*, but I'm all too familiar with situations where features that were previously free of charge suddenly grow a monthly per-X fee.

That said, it probably would be worth Sonatype's time to take at least the handful of most upvoted issues from JIRA and migrate them to Github themselves (with or without automation), rather than asking users to do it.

**Comment by nblair** [comment]
We've just sent the second and final notice as a comment on open issues. We are still on track for the change to occur next week. 

We appreciate the community adopting this new forum. We just had our first weekly triage call with the product team, and we've closed or updated a number of tickets with the pending column. There's still more to catch up with, more than we've had time to get through in this first run. We'll commit to reviewing items with that pending label every week on Tuesdays.

I intend to close this issue on Tuesday May 23.

**Comment by ite-klass** [comment]
You may want to pin this issue for discoverability. _(That should be possible?)_

**Comment by ite-klass** [comment]
As a tip for anyone migrating a ticket; you can [archive the ticket webpage on archive.org)(https://web.archive.org/save/) and reference/link it. That way that historic ticket content will be referable/inspectable. I've done so in the ones I created.

**Comment by nblair** [comment]
Our issue tracker migration is green-lit and activities will commence tomorrow. In the afternoon (eastern) access to our on-premise Jira instance will close.

Thank you for your understanding and willingness to engage here!

**Comment by soc** [comment]
So, if I wanted to publish a new artifact, where would I do this?

(The [documentation](https://central.sonatype.org/publish/publish-guide/#initial-setup) links to the discontinued JIRA instance which itself links to this repository.)

**Comment by JayStGelais** [comment]
@nblair 

Not sure if I'm reading this change correctly, as the OSS publishing docs still point to the Jira instance...

If we need to add a user to our project, do we add a GitHub issue here or still use the linked Jira instance? 

trying to follow the steps here: https://central.sonatype.org/publish/manage-permissions/

**Comment by nblair** [comment]
@soc and @JayStGelais - publishing your open source artifacts to Maven Central is unchanged and unaffected by this Jira migration (so far). https://central.sonatype.org/publish/publish-guide/ is still the right place to follow, you'll still be able to access the Jira projects they use at issues.sonatype.org for the next few months.

**Comment by soc** [comment]
@nblair Thanks!

**Comment by iseki0** [comment]
@nblair  So there's no way to see the old issues? Maybe you(I mean sonatype, not you personal) can provide a readonly archive to save the history? Let the history disappeared  is never a good choice.😃

**Comment by moisesarrona** [comment]
Hi, @nblair 
When logging into our Nexus instance, it shows us the following error:
_Incorrect username, password or no permission to use the Nexus User Interface.
Try again. Please [login](http://mvnrepositorio.primeraplus.com:8081/nexus) before attempting further requests._
Is it due to tracker migration?

My version of nexus is 2.14.5-02

**Comment by nblair** [comment]
Hi @moisesarrona - no, the error you see is not related to the Issue tracker migration. You'll need to follow up with your organization's Nexus Repository administrator to troubleshoot authenticating to your local instance.

**Comment by xiaodizi** [comment]
I didn't understand what was suspended and now my account can't be logged in. Clicking sign in is 403 Forbidden. I want to publish a jar of my own.
