### ISSUE TITLE
Nexus still makes bundler fall back to the full index resolution since compact index methods are not supported

### ISSUE THREAD

**Issue by LukeIGS** [sonatype/nexus-public#108]
Currently when running a fresh bundle install/bundle update against a nexus repository, that repository will return a 404 on `/gem/info/{gem}` causing bundler to fall back to dependency api based resolution, which is quite slow (as established in https://issues.sonatype.org/browse/NEXUS-31225, and https://issues.sonatype.org/browse/NEXUS-17626.)  This affects both enterprise and oss users.

**Comment by nblair** [comment]
Thanks for opening an issue @LukeIGS. I'll need a little more detail, we just opened up Github Issues on this project. Were you presented an issue template with a list of questions to follow? I'm hoping we can start there first.

**Comment by LukeIGS** [comment]
Sorry, there's more information in my last comment on https://issues.sonatype.org/browse/NEXUS-31225
I was, i just didn't want to restate everything in the jira issue.

Given the following configuration:
A group named `gem` containing
  - A hosted repository named `local-ruby`
     * A set of local gems named localgem0 to localgem4
  - A proxy repository pointed at `https://rubygems.org/` named `rubygems`

Running `bundle upgrade --verbose` will return something along these lines
https://hastebin.com/share/omabififec.log
It properly resolves the version list, however when it tries querying gem info against any of the local gems, it ends up returning a 404, which makes bundler fall back to dependency api, causing slowness.

**Comment by nblair** [comment]
Thanks - the issue you refer to is closed as fixed in Release 3.53.0, so we would prefer to isolate your report to a new clean issue here (per #105). The information from [the template](https://github.com/sonatype/nexus-public/blob/main/.github/ISSUE_TEMPLATE/issue-template.md) about your environment would be helpful for us to understand your report more clearly.

**Comment by LukeIGS** [comment]
## What problem are you trying to solve?

Bundler resolution falls back to dependency api when attempting to get gem info endpoints for hosted gems as seen in the following log.
https://hastebin.com/share/omabififec.log

## Do you have a workaround you are using at present?
No

## What feature or behavior is this required for?

Hosted Ruby Repositories

## How could we solve this issue? (Not knowing is okay!)
Implement the info endpoint to prevent bundler from falling back to the dependency api (man it sure would be great if they had these apis documented somewhere easy to get at that wasn't a blog post with an incorrectly named endpoint.)
https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/
the deps endpoint is renamed info in practice.  An example of what it returns would be https://rubygems.org/info/rails

## Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Node: Azure Kubernetes Service Standard_DS3_v2 Node 
License: OSS
OS: Linux
DB: N/A
Image: sonatype/nexus3:3.53.0
Resource Limits: 8 Gi, 4000m

**Comment by nblair** [comment]
Thank you for the additional details. We'll review this internally as an idea for product improvement with our product team.

**Comment by vswaminathan777** [comment]
@Annih Please upgrade to the latest version of Nexus Repository 3.53.1 for the fix.  if you have already upgraded and still facing the same issue, please verify sonatype-work/nexus3/logs/tasks/ directory for repository.ruby.rebuild.attributes*.log and repository.rubygems.generate-sha256-checksums-*.log to see whether any errors have occurred.

**Comment by Annih** [comment]
OK @vswaminathan777 I confirm the `/info/<gem>` is implemented for hosted repo in 3.53.1.
However I do have errors in the file you mentioned and I'm not sure how I should fix them.

I'll create new issues

**Comment by Annih** [comment]
I confirm on my side the `/info/<gem>` & `/versions` are implemented.
We faced some issues due to the size of one of our repo, but apart from that it works.

Note that there should be another global endpoint the `/names`, which is not implemented in Sonatype Nexus.

**Comment by marvinthepa** [comment]
> We've since migrated to another solution so i can't provide input.

Would you be willing to share which solution correctly implements the compact index API?
