### ISSUE TITLE
nexus-staging-maven-plugin deploy goal injection not invoked on maven 4

### ISSUE THREAD

**Issue by lprimak** [sonatype/nexus-public#109]
Version .13 of the plugin (latest) fails with maven 4
The "magic" where it replaces deploy plugin execution with maven staging plugin execution is failing, and the plugin isn't invoked while it was invoked in maven 3.
See maven issue for more details: 
https://issues.apache.org/jira/browse/MNG-7627

**Comment by lprimak** [comment]
Thanks Peter!.
The issue is not that simple because it requires a "test" release cycle and credentials.
The problem can be reproduced with  https://github.com/flowlogix/flowlogix/tree/Version-5.1 but any project will do that follows what's written in https://central.sonatype.org/publish/publish-maven/#review-requirements
 The command line is "mvn release:prepare release:peform"

**Comment by nblair** [comment]
Thanks @lprimak for opening an issue. As mentioned in #105, this is a new forum for us. 

When you first created the issue, were you presented with a template of pre-filled questions? These questions are important for us being able to help you, and I want to confirm that community members are seeing that template.

We originally envisioned this forum for providing support to users of Sonatype Nexus Repository OSS. The plugin you mention is part of a separate project - https://github.com/sonatype/nexus-maven-plugins. Issues isn't open there, but it's something I'll have to explore. I recognize we previously just used he NEXUS jira for all things related to Nexus Repository OSS.

With regards to your specific question, we have not explored support for Maven 4 for that plugin previously, nor is it being considered in our near term plans.
