### ISSUE TITLE
p2 Hosted repository support for Nexus

### ISSUE THREAD

**Issue by hansbeld** [sonatype/nexus-public#111]
Hosting and deploying the p2 repositories directly to the Nexus would be a huge favor as this would provide a better overview and handling for users which have no access to the filesystem. Our Eclipse RCP projects depend on a p2 hosted repo for publishing developed plugins. It is difficult to argue internally for Nexus as our single, trustable source of software components if a part of our development projects are not supported.

**Comment by nblair** [comment]
Thank you @hansbeld for the enhancement idea. We'll review with the product team at our next triage.

**Comment by bjmi** [comment]
* preceded issue [NEXUS-22938](https://issues.sonatype.org/browse/NEXUS-22938)
* p2 hosted repository support in Nexus **3**
