### ISSUE TITLE
[NEXUS-36614] The "dockerProxy.useTrustStoreForIndexAccess" field is missing in the REST API for proxied Docker repositories

### ISSUE THREAD

**Issue by TheLastProject** [sonatype/nexus-public#112]
_(Manually copied from https://issues.sonatype.org/browse/NEXUS-36614 as that JIRA is going to be shut down but the issue is not resolved yet)_

The /v1/repositories/docker/proxy/\{repositoryName} endpoint in Sonatype Nexus does not return the useTrustStoreForIndexAccess field under dockerProxy.

How to reproduce:
1. Create a docker proxy repository
2. Ensure the second "Use the Nexus Repository truststore:" option is checked
![image](https://github.com/sonatype/nexus-public/assets/1885159/ddf67c02-1dbb-4692-b422-adc5a2a31056)
3. Request the endpoint through the API (in my example it's named docker.io):

```
curl -X 'GET' \
 'http://your_ip:8081/service/rest/v1/repositories/docker/proxy/docker.io' \
 -H 'accept: application/json'
```

 4. Observe there is only a single truststore related entry in the output and it is false

```
{
  "name": "docker.io",
  "url": "http://your_ip:8081/repository/docker.io",
  "online": true,
  "storage": {
    "blobStoreName": "default",
    "strictContentTypeValidation": true,
    "writePolicy": "ALLOW"
  },
  "cleanup": null,
  "docker": {
    "v1Enabled": true,
    "forceBasicAuth": true,
    "httpPort": null,
    "httpsPort": null,
    "subdomain": null
  },
  "dockerProxy": {
    "indexType": "HUB",
    "indexUrl": null,
    "cacheForeignLayers": false,
    "foreignLayerUrlWhitelist": []
  },
  "proxy": {
    "remoteUrl": "https://registry-1.docker.io",
    "contentMaxAge": 1440,
    "metadataMaxAge": 1440
  },
  "negativeCache": {
    "enabled": true,
    "timeToLive": 1440
  },
  "httpClient": {
    "blocked": false,
    "autoBlock": false,
    "connection": {
      "retries": null,
      "userAgentSuffix": null,
      "timeout": null,
      "enableCircularRedirects": false,
      "enableCookies": false,
      "useTrustStore": false
    },
    "authentication": null
  },
  "routingRuleName": null,
  "format": "docker",
  "type": "proxy"
}
```

Note: the relevant HTML element for the checkbox contains the following:
```
name="attributes.dockerProxy.useTrustStoreForIndexAccess"
```

It is also impossible to update this value through the API, as sending the dockerProxy.useTrustStoreForIndexAccess key will not change the setting (and thus updating the settings through the API will always uncheck this checkbox). This makes it impossible to use the API safely for Docker proxy repositories that need this setting.

**Comment by nblair** [comment]
Thank you @TheLastProject  for the enhancement idea. We'll review with the product team at our next triage.
