### ISSUE TITLE
[NEXUS-26814] maven-metadata.xml files are not removed, causing slowness when fetching them

### ISSUE THREAD

**Issue by flitzie** [sonatype/nexus-public#114]
* Back to previous view <https://issues.sonatype.org/browse/NEXUS-26814>

      [NEXUS-26814] maven-metadata.xml files are not removed, causing
      slowness when fetching them
      <https://issues.sonatype.org/browse/NEXUS-26814> Created: 02/23/21
       Updated: 05/10/23

*Status:* 	New
*Project:* 	Sonatype Nexus Repository
<https://issues.sonatype.org/secure/BrowseProject.jspa?id=10001>
*Component/s:* 	Maven
<https://issues.sonatype.org/issues/?jql=project%3D10001%20AND%20%22component%22%3D15178%20ORDER%20BY%20priority%20ASC>
*Affects Version/s:* 	3.22.1
<https://issues.sonatype.org/issues/?jql=project%3D10001%20AND%20%22affectedVersion%22%3D19229%20ORDER%20BY%20priority%20ASC>, 3.29.2 <https://issues.sonatype.org/issues/?jql=project%3D10001%20AND%20%22affectedVersion%22%3D21031%20ORDER%20BY%20priority%20ASC>, 3.30.0 <https://issues.sonatype.org/issues/?jql=project%3D10001%20AND%20%22affectedVersion%22%3D20939%20ORDER%20BY%20priority%20ASC>
*Fix Version/s:* 	None

*Type:* 	Bug 	*Priority:* 	Minor
*Reporter:* 	Louis-Rémi Paquet
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=lrp>
*Assignee:* 	Unassigned
*Resolution:* 	Unresolved 	*Votes:* 	3
*Labels:* 	migration-announce, performance, triaged
*Remaining Estimate:* 	Not Specified
*Time Spent:* 	Not Specified
*Original Estimate:* 	Not Specified

*Attachments:* 	PNG File image-2021-02-23-17-33-38-366.png    
*Issue Links:* 	
*Relates*
relates 	NEXUS-25287 <https://issues.sonatype.org/browse/NEXUS-25287>
Rebuild maven metadata task does not ... 	Open

*Last Updated By:* 	Nicholas Blair Nicholas Blair
*Date of First Response:* 	23/Feb/21 10:46 PM

 *Description*  	 

We ran into the issue of slowness (20s or more) to get maven-metadata files.

This happened for numerous artifacts under the same groupId.

All these tasks were run with no success of deleting thexe
maven-metadata.xml files

  * Repair - Rebuild Maven repository metadata (maven-metadata.xml)
    <https://help.sonatype.com/repomanager3/system-configuration/tasks#Tasks-Repair-RebuildMavenrepositorymetadata(maven-metadata.xml)>
  * Maven - Delete SNAPSHOT
    <https://help.sonatype.com/repomanager3/system-configuration/tasks#Tasks-Maven-DeleteSNAPSHOT>
  * Cleanup Repositories using their associated policies (with policies
    defined on the right groupId)
  * Rebuild Repository Index
  * Compact blob store (probably not related but we tried everything )

Artifacts are, in fact, cleaned but maven-metadata.xml are still there.

After manually, through the UI, removing all these leftover files for a
particular groupId, fetching maven-metadata under this groupId was fast
again.

This was seen on 3.22.1 and 3.29.2 on our side but may affect other
versions as well.

 *Comments*  	 

Comment by Joe Tom [X] (Inactive)
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=jtom> [
02/23/21 ]

Possibly duplicate of NEXUS-25287
<https://issues.sonatype.org/browse/NEXUS-25287>?

It is not clear to me from the summary/description if the issue is the
slowness or the issue is the repair. If the repair seems like a likely
dup. If the slowness, I suspect we'd need more info.

Comment by Louis-Rémi Paquet
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=lrp> [ 02/23/21 ]

The issue here is the maven-metadata.xml files not being deleted when
the artifacts are.

Slowness is the symptom of this issue.

We experienced slowness which, according to our conclusions, is due to
the too great number of maven-metadata.xml files inside a specific
artifactId (one per each snapshot versions)

 

Comment by Joe Tom [X] (Inactive)
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=jtom> [
02/23/21 ]

Ah I see. So then 25287 is just probably why your task fix attempts
failed. Thanks for clarify.

Comment by Joe Tom [X] (Inactive)
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=jtom> [
02/23/21 ]

I can reproduce this behavior by manually deleting every asset (via browse).
The behavior does not seem reproducable if I delete the component (which
iiuc would also include delete via search as I believe that just shows
components).
There doesn't seem to be a workaround outside of further manual deletion
(given the linked ticket).

Comment by Louis-Rémi Paquet
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=lrp> [ 02/24/21 ]

So, yes it's a duplicate if, when running the cleanup task, the
maven-metadata.xml is being removed when the assets are.

However, I'm still trying to find a way to delete them automatically and
in batch. We have a lot of them.

Comment by Joe Tom [X] (Inactive)
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=jtom> [
02/24/21 ]

Sorry if I wasn't clear, it's not a duplicate IMO now that I understand
your issue. Cleanup is a workaround, but it shouldn't behave that way.
This ticket is the cause. Will let triage team disagree with me when we
get there. Thanks for your patience and report.

Comment by Bas
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=Popo> [
04/05/21 ]

Any news on this? This has been plaguing our CI/CD setup for months now.
We've got thousands upon thousands of useless
maven-metadata.xml/maven-metadata.xml.md5/maven-metadata.xml.sha1 files.

We've even seen Jenkins builds start to fail because Nexus is taking too
long to respond to requests.

Comment by R. Fitzner
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=fitzner> [
06/27/22 ]

Dear Sonatype team,

since there is not update on this issue so far, can you please provide a
groovy script to clean up theses undetached metadata.xml files (incl.
matching checksum files) please?

Thank you for your help in advance.

Comment by Nicholas Blair
<https://issues.sonatype.org/secure/ViewProfile.jspa?name=nblair> [
05/10/23 ]

Sonatype will retire our public-facing Jira instances on May 25, 2023.
This includes https://issues.sonatype.org/browse/NEXUS
<https://issues.sonatype.org/browse/NEXUS>. The decision is necessitated
by a need for increased security as well as to replace a system that is
almost at “end of life” with Atlassian.

Moving forward, please watch the Release Notes
<https://help.sonatype.com/repomanager3/product-information/release-notes> for a list of issues fixed in each product release.

Customers with active subscriptions to Sonatype solutions may report
defects by raising a support incident at: https://support.sonatype.com
<https://support.sonatype.com/>.

Users of Sonatype Nexus Repository OSS should file issues in:
https://github.com/sonatype/nexus-public
<https://github.com/sonatype/nexus-public>. Please see
https://github.com/sonatype/nexus-public/issues/105
<https://github.com/sonatype/nexus-public/issues/105> for more details.

Generated at Fri May 12 07:48:15 UTC 2023 using Jira
9.4.2#940002-sha1:46d1a51de284217efdcb32434eab47a99af2938b.

**Comment by nblair** [comment]
hi @flitzie - thanks for opening this issue. Since this is a copy of an existing issue verbatim, I'm inclined to close it as a duplicate. 

If you continue to experience this issue in the latest version of Sonatype Nexus Repository, we'd prefer if you created a new issue, and respond in detail to the questions in our new issue template.

Thanks!
