### ISSUE TITLE
[NEXUS-31461] Unpredictable sort order for Maven versions

### ISSUE THREAD

**Issue by bendem** [sonatype/nexus-public#116]
Status:	New
Project:	Sonatype Nexus Repository
Component/s:	Maven, REST, Search
Affects Version/s:	3.38.0, 3.38.1, 3.40.1, 3.46.0, 3.48.0
Fix Version/s:	None

Type:	Bug	Priority:	Major
Reporter:	Hardeep Nagra	Assignee:	Unassigned
Resolution:	Unresolved	Votes:	19
Labels:	migration-announce, regression, sam-cashew, supportant
Remaining Estimate:	Not Specified
Time Spent:	Not Specified
Original Estimate:	Not Specified

Attachments:	PNG File image-2022-05-31-11-54-54-452.png    
Issue Links:	
Caused
is caused by	NEXUS-28918	Search API for maven format does not ...	Closed
Duplicate
Relates
is related to	NEXUS-30694	Sorting Maven components with Version...	Closed
Last Updated By:	
Nicholas Blair
 Nicholas Blair
Date of First Response:	08/Mar/22 3:01 PM
Story Points:	5
Team:	NXRM - Mad Max
Notability:	3
Impact:	2

 **Description** 	 
A follow-up to NEXUS-30694, the same issue is still occurring for maven versions where a random order is being returned.

To reproduce:

1. Uploaded two snapshots to 3.38:

mvn deploy:deploy-file -DgroupId=com.foo.hsmservice.service -DartifactId=hsmservice-deployment -Dversion=1.31-us_481184_luigi__migration_2-SNAPSHOT -DgeneratePom=true -Dpackaging=jar -DrepositoryId=nexus -Durl=http://localhost:8081/repository/maven-snapshots -Dfile=./testjar.jar
2. Call the search/assets/download REST API, to retrieve the latest version e.g. 

curl -v -u admin:admin123 "http://localhost:8081/service/rest/v1/search/assets/download?sort=version&repository=maven-snapshots&maven.groupId=com.foo.hsmservice.service&maven.artifactId=hsmservice-deployment&maven.baseVersion=1.31-us_481184_luigi__migration_2-SNAPSHOT&maven.extension=jar" 
And note the version returned.

3. Then repeat steps 1-2 again and note that the latest timestamped snapshot is not returned. Instead the order is random.

Potential Cause:

For the given version strings e.g.

1.31-us_481184_luigi__migration_2-20220312.160843-37
1.31-us_481184_luigi__migration_2-20210419.153348-38
It seems to be much the same as NEXUS-30694 where the "normalized_version" is returning the same values resulting in an unpredictable order e.g.

jshell> versionNormalizer.getNormalizedValue("1.31-us_481184_luigi__migration_2-20210412.160843-37");
$27 ==> "000000001.000000031.000000000.b.us_-000481184-_luigi__migration_000000002"
jshell> versionNormalizer.getNormalizedValue("1.31-us_481184_luigi__migration_2-20210419.153348-38");
$28 ==> "000000001.000000031.000000000.b.us_-000481184-_luigi__migration_000000002"
However please be aware it is not just Snapshot versions affected, Release versions with a similar string also have the same issue e.g.

jshell> versionNormalizer.getNormalizedValue("1.31-us_481184_luigi_migration-1");
$8 ==> "000000001.000000031.000000000.e.us_-000481184-_luigi_migration"
jshell> versionNormalizer.getNormalizedValue("1.31-us_481184_luigi_migration-2");
$9 ==> "000000001.000000031.000000000.e.us_-000481184-_luigi_migration"
Expected:

Versions should be sorted in alpha-numeric order.

 

 

 **Comments** 	 
Comment by José Coelho [ 05/30/22 ]
I'm experiencing this same issue in Nexus 3.38.1-01

 

Comment by Laurent Thoulon [ 05/31/22 ]
Adding a screenshot of the issue on my end. We use a versioning system that integrates the timestamp and as you can see the timestamps are not in the proper order.

![image](https://github.com/sonatype/nexus-public/assets/2681677/e6adf30f-2aae-43fc-bdcf-94098dada410)

Comment by Arnab [ 07/05/22 ]
Adding some observations on the issue for SNAPSHOT versions (on 3.38.1-01):

The same search endpoint (service/rest/v1/search/assets) returns different ordering and different latest version for the same G, A, V, Extension & Classifier combination.
Not only the latest version is returned incorrectly (less frequent), order of appearance for rest of the available version is also random in nature.
In my test example following was the returned order in two different times for the same URL (expected descending order)
-7, -8, -1, -4, -2, -3, -5, -6
-8, -4, -5, -6, -7, -1, -2, -3

This doesn't sort with the timestamp as well, it's not deterministic in that way either. 
Comment by art lucero [ 07/14/22 ]
still an issue on 3.40.1-01

Comment by Benjamin Peter [ 07/27/22 ]
We also have this issue. I found this command helpful to see if we also had the problem.

http https://nexus/service/rest/v1/search/assets\?sort\=version\&repository\=myrepo\&maven.groupId\=mygid\&maven.artifactId\=myid\&maven.baseVersion\=1.0.0-RC-SNAPSHOT\&maven.extension\=jar --pretty=none | jq '.items[] | .maven2.version' | uniq
Comment by bendem [ 08/23/22 ]
Would like to add that ascending sort works fine, it's just the descending sort that's broken:

> curl '$API/search/assets/?sort=version&direction=desc&repository=maven-snapshots&maven.extension=war&maven.groupId=be.liege.cti.population&maven.artifactId=population-web-service&maven.baseVersion=7.0.3-WOCODO-SNAPSHOT&maven.classifier=' | jq -r '.items[].maven2.version'
7.0.3-WOCODO-20220823.065340-10
7.0.3-WOCODO-20220823.073743-11
7.0.3-WOCODO-20220823.081558-12
7.0.3-WOCODO-20220823.081622-13
7.0.3-WOCODO-20220822.074517-9
7.0.3-WOCODO-20220819.073504-8
7.0.3-WOCODO-20220223.142723-7

> curl '$API/search/assets/?sort=version&direction=asc&repository=maven-snapshots&maven.extension=war&maven.groupId=be.liege.cti.population&maven.artifactId=population-web
-service&maven.baseVersion=7.0.3-WOCODO-SNAPSHOT&maven.classifier=' | jq -r '.items[].maven2.version'
7.0.3-WOCODO-20220223.142723-7
7.0.3-WOCODO-20220819.073504-8
7.0.3-WOCODO-20220822.074517-9
7.0.3-WOCODO-20220823.065340-10
7.0.3-WOCODO-20220823.073743-11
7.0.3-WOCODO-20220823.081558-12
7.0.3-WOCODO-20220823.081622-13

 

Comment by bendem [ 08/23/22 ]
Nevermind, it just worked by mistake. I have the same behavior now:

> curl -s '$API/search/assets/?sort=version&direction=asc&repository=maven-snapshots&maven.extension=war&maven.groupId=be.liege.cti.population&maven.artifactId=population-web-service&maven.baseVersion=7.0.3-WOCODO-SNAPSHOT&maven.classifier=' | jq -r '.items[].maven2.version'
7.0.3-WOCODO-20220223.142723-7
7.0.3-WOCODO-20220819.073504-8
7.0.3-WOCODO-20220822.074517-9
7.0.3-WOCODO-20220823.065340-10
7.0.3-WOCODO-20220823.081622-13
7.0.3-WOCODO-20220823.073743-11
7.0.3-WOCODO-20220823.081558-12
7.0.3-WOCODO-20220823.085042-14

Comment by Jan Wedding [ 01/31/23 ]
Any plans to get this fixed or any workaround to get results in a stable order?

Comment by BMW FS IT [ 03/22/23 ]
Hello, 

We are also interested in a fix for this issue. Can you please provide an update with an expected date when this will be fixed?

 

Thank you!

 

Comment by Alexandre Chatiron [ 05/07/23 ]
I push a pull request for this problem https://github.com/sonatype/nexus-public/pull/107 , seems to fix the problem for me 

 

Can you check it  ?

Thanks

Comment by Nicholas Blair [ 05/10/23 ]
Sonatype will retire our public-facing Jira instances on May 25, 2023. This includes https://issues.sonatype.org/browse/NEXUS. The decision is necessitated by a need for increased security as well as to replace a system that is almost at “end of life” with Atlassian.

Moving forward, please watch the Release Notes for a list of issues fixed in each product release.

Customers with active subscriptions to Sonatype solutions may report defects by raising a support incident at: https://support.sonatype.com.

Users of Sonatype Nexus Repository OSS should file issues in: https://github.com/sonatype/nexus-public. Please see https://github.com/sonatype/nexus-public/issues/105 for more details.

Generated at Fri May 12 08:46:24 UTC 2023 using Jira 9.4.2#940002-sha1:46d1a51de284217efdcb32434eab47a99af2938b.

**Comment by nblair** [comment]
Thanks @bendem - we already have this tracked in a few places, including #107. We are looking at this internally, so I'm going to close as a duplicate.

**Comment by OmarHawk** [comment]
How is the status about this @nblair? Now that there is no open public issue about this anymore, and only an orphaned Pull Request (seems like no Pull Requests are considred at all...), it seems that the whole process of reporting things and (even contributing to) get things fixed became sort of intransparent.

**Comment by nblair** [comment]
Hi @OmarHawk - we actually just accepted a community contribution (see #107) in order to fix this bug. The work to complete the task has been assigned to an engineering team and the contribution is expected to be delivered in a future release.

**Comment by OmarHawk** [comment]
Nice!

**Comment by bendem** [comment]
It looks like this was fixed in https://github.com/sonatype/nexus-public/releases/tag/release-3.57.0-01, but it introduced https://github.com/sonatype/nexus-public/issues/188.
