### ISSUE TITLE
[NEXUS-35956] docker group does not return Link header (pagination feature)

### ISSUE THREAD

**Issue by jgarec** [sonatype/nexus-public#117]
Original issue : https://issues.sonatype.org/browse/NEXUS-35956

This issue is related with [NEXUS-26037](https://issues.sonatype.org/browse/NEXUS-26037).

Pagination works if i access the proxy repository :
`curl -k -v https://<nexus_host>:8087/v2/renovate/renovate/tags/list\?n\=10`
The header link is returned as expected :
`< Link: <https://<nexus_host>:8087/v2/renovate/renovate/tags/list?n=10&last=0.0.4-slim>; rel="next"`

But if this repository is inside a docker group then the Link header is not returned and it breaks the pagination.

**Comment by nblair** [comment]
This item is on our radar and has an internal ticket. Please follow the release notes for updates. Will close the issue here as a duplicate.
