### ISSUE TITLE
[NEXUS-23658] npm Audit support in Nexus Repository without an IQ server

### ISSUE THREAD

**Issue by marob** [sonatype/nexus-public#119]
Original issue: https://issues.sonatype.org/browse/NEXUS-23658

`npm audit` command should work (without the need of adding IQ server) when using Nexus as repository.

I suppose Nexus could easily proxy the "audit" requests to https://registry.npmjs.org/

**Comment by gandadil** [comment]
We can't run npm install/update because it runs audit every time. The npm audit on install can't change the registry URL, just on npm audit alone, so we have a problem here.
