### ISSUE TITLE
[NEXUS-16089] terraform registry format support

### ISSUE THREAD

**Issue by dmpe** [sonatype/nexus-public#120]
* What problem are you trying to solve?

https://issues.sonatype.org/browse/NEXUS-16089

Hi @nblair, can you please add terraform registry into Nexus? Would have been amazing. 

* Do you have a workaround you are using at present?

no

* What feature or behavior is this required for?

to upload terraform plugins/modules to nexus terraform hosted repository

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

latest Nexus 3 OSS

- https://developer.hashicorp.com/terraform/registry/private
- https://developer.hashicorp.com/terraform/registry/api-docs
- community project: https://github.com/davejab/nexus-repository-terraform

Thank you.

**Comment by alan-czajkowski** [comment]
@nblair this has been requested on ideas.sonatype.com IDEAS-I-1330 over 2 years ago, the demand is really high, especially when JFrog Artifactory already supports this, when can we expect this to be supported?

**Comment by laxmi-st** [comment]
Terraform Proxy support is now available in [Nexus Repository 3.88.0](https://help.sonatype.com/en/sonatype-nexus-repository-3-88-0-release-notes.html#support-for-proxy-terraform-repositories)
