### ISSUE TITLE
When running behind IIS as a reverse proxy, error message "Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)" appears

### ISSUE THREAD

**Issue by gschizas** [sonatype/nexus-public#121]
### What problem are you trying to solve?

(Migrated from Jira - [NEXUS-21834](https://issues.sonatype.org/browse/NEXUS-21834?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel))

I've setup Nexus on Windows, using IIS as a reverse proxy, and I created some APT repositories.

I've successfully uploaded a couple of packages in it, but when I try doing apt-get update from a client (especially an older one), I get the following error:

`Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)`

After some research, it seems that the problem is that IIS (being on Windows) sends the `InRelease` file with CRLF instead of LF. If I manually (I'm using Fiddler as a proxy-in-the-middle) remove the CR characters from the output, `apt-get update` works perfectly (I've managed to install a couple of packages).

### Do you have a workaround you are using at present?

I managed to do a workaround, using URL rewrite.
Add this to web.config:

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <outboundRules>
                <rule name="Replace CRLF with LF" preCondition="ReleaseFile">
                    <match filterByTags="None" pattern="\r" />
                    <action type="Rewrite" value="" />
                </rule>
                <preConditions>
                    <preCondition name="ReleaseFile">
                        <add input="{REQUEST_URI}" pattern="/repository/([-a-z0-9]*)/dists/(\w*)/InRelease" />
                    </preCondition>
                </preConditions>
            </outboundRules>
        </rewrite>
    </system.webServer>
</configuration>
```

And then it just works!

The REQUEST_URI does most of the heavy lifting. It should work for most cases, but if it doesn't, it's easy to extend the regular expression, or even hardcode the URL for the repo.

This is still just a workaround, but it's one that works without any changes to the code.

### What feature or behavior is this required for?

This is required to host an apt repository on a nexus instance running on Windows, using IIS as a reverse proxy.

### How could we solve this issue? (Not knowing is okay!)

I had made a patch and pull request for the fix from when nexus-repository-apt was a separate plugin. It was a simple fix, really, just replace `\r` with the empty string. The [original pull request](https://github.com/sonatype-nexus-community/nexus-repository-apt/pull/98/files) probably doesn't work as-is anymore, because the file has changed since then, but the principle remains the same: Add these three lines before signing the release files:

```
releaseFile = releaseFile.replace("\r", "");
inRelease = new String(inRelease, Charsets.UTF_8).replace("\r", "").getBytes();
releaseGpg = new String(releaseGpg, Charsets.UTF_8).replace("\r", "").getBytes();
```

### Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

It's been a very long time since I opened this bug, but it's still there on **Nexus 3.53.0-01**, on **Windows Server 2022 21H2**, using the default database (**Embedded OrientDB**)

**Comment by mrprescott** [comment]
Given the sensitivity of this area, the workaround looks like the best path forward for this particular bit of friction.

**Comment by gschizas** [comment]
I disagree - this is still a problem when running on Windows. I just happened to already use IIS as a reverse proxy on other things. And it's a silly bug all in all.
