### ISSUE TITLE
[NEXUS-26802] "Unable to show requested tree entry" when refreshing after last entry was deleted

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#122]
Nexus version OSS 3.34.1-01

If you are browsing a repository and delete the last entry, then press the Refresh button in the upper right, you get the error "Unable to show requested tree entry" shown.

**Comment by nblair** [comment]
3.34 is old; I see we haven't closed NEXUS-26802, but I'm curious if this still happens with a more recent version of Sonatype Nexus Repository.

**Comment by nblair** [comment]
I'm not seeing this behavior any more in contemporary versions, closing as fixed.
