### ISSUE TITLE
[NEXUS-28610] Typo in Directories documentation

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#125]
Nexus version OSS 3.33.0

Maybe it is because I'm not a native speaker, but "to out" does not seem to be the right verb here:

> These log files include messages that would typically be too noisy to out into the main application log.

If it is, just ignore me and close the ticket. :-)

Found on https://help.sonatype.com/repomanager3/installation/directories

**Comment by Vampire** [comment]
Comment by "Joe Tom":

Probably should be "output" but even that's a bit of a stretch. Thanks for the report, I noted to our technical writing staff.

**Comment by lisadurant** [comment]
Fixed. Please note new URL as topic has moved: https://help.sonatype.com/repomanager3/installation-and-upgrades/directories
