### ISSUE TITLE
[NEXUS-28671] Possible Typo in "Searching for Components" doc

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#126]
Nexus version OSS 3.33.0

Found on https://help.sonatype.com/repomanager3/user-interface/searching-for-components:

> (imagine wanting to search for "aether-util" (see below for more details on double quotes), this would require the full name to match against, rather than a tokenized version)

 should probably be (code format for "aether-util")

> (imagine wanting to search for `"aether-util"` (see below for more details on double quotes), this would require the full name to match against, rather than a tokenized version)

**Comment by lisadurant** [comment]
fixed.
