### ISSUE TITLE
[NEXUS-28700] Formatting error in "Privileges" doc

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#129]
Nexus version OSS 3.33.0

Found on https://help.sonatype.com/repomanager3/system-configuration/access-control/privileges:

![image](https://github.com/sonatype/nexus-public/assets/325196/4a7c2d05-3b39-4b99-bd97-a6fb8a660a12)

should probably be

![image](https://github.com/sonatype/nexus-public/assets/325196/6f16d581-30d3-4678-b3f1-d13b3d532d8a)

**Comment by lisadurant** [comment]
fixed.
