### ISSUE TITLE
[NEXUS-28707] Formatting error in "Storage Guide" doc

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#132]
Nexus version OSS 3.33.0

Found on https://help.sonatype.com/repomanager3/repository-management/storage-guide:
![image](https://github.com/sonatype/nexus-public/assets/325196/6dbc4398-b8c9-4ea9-83ef-d9591033e957)

should be

![image](https://github.com/sonatype/nexus-public/assets/325196/c5e75fa4-fa53-4653-806e-8e99261b5777)

**Comment by nblair** [comment]
The link you shared is no longer present in our help documentation. Contemporary versions of Nexus Repository have different documentation entry points and updated links for storage help.
