### ISSUE TITLE
[NEXUS-28906] Updating or creating a repository with non-existent routing rule via REST does not fail

### ISSUE THREAD

**Issue by Vampire** [sonatype/nexus-public#133]
Nexus version OSS 3.33.0

I update or create repositories via REST API.
While doing so, I also configure routing rules.
If you update or create a repository with a non-existing routing rule,
the request is simply successful without a routing rule being set.
Instead I'd have exepcted the call to fail.

**Comment by nblair** [comment]
3.33 is old; I see we haven't closed NEXUS-26906, but I'm curious if this still happens with a more recent version of Sonatype Nexus Repository. There have been numerous improvements to the REST API in that time and we believe this may have already been addressed.
