### ISSUE TITLE
Docker proxy for gitlab.com repository

### ISSUE THREAD

**Issue by ivan-morhun** [sonatype/nexus-public#143]
I'm trying to set up a docker proxy for gitlab.com docker registry and nothing works.

Is there somebody who successfully managed this? Could you please share the working configuration?

Also, it will be a good option to have a collection of the most popular registry setups. E.g. google, docker, etc

Thanks in advance!

**Comment by nblair** [comment]
Thanks for filing this @ivan-morhun. We don't have access to a gitlab.com docker registry to try this, so I'm sorry we can't help right away. Is there someone from the community that's tried this?

**Comment by ivan-morhun** [comment]
It's publicly accessible and if somebody tried to configure a proxy for it, please share the configuration.
Here is the URL registry.gitlab.com
