### ISSUE TITLE
NEXUS-17671 Provide a REST API for cleanup policies

### ISSUE THREAD

**Issue by stevehipwell** [sonatype/nexus-public#149]
* What problem are you trying to solve?
I'd like to be able to create and manage cleanup policies via the REST API

* Do you have a workaround you are using at present?
I use the script REST API to script cleanup policies

* What feature or behavior is this required for?
IaC provisioning of Nexus3

* How could we solve this issue? (Not knowing is okay!)
Implement a REST interface for cleanup policies

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Latest version running on Kubernetes using OrionDB.

* Anything else?
I [requested this](https://issues.sonatype.org/browse/NEXUS-17671) almost 5 years ago.

**Comment by nblair** [comment]
Thanks for opening this @stevehipwell, we will keep this open to gauge demand.

**Comment by eriklogtenberg** [comment]
Actually, it would be really nice to  be able to fully configure Nexus through the API. This would aid automatic deployment through our CI/CD pipeline significantly.

**Comment by tutNichts** [comment]
I would also greatly appreciate this. For my scripted Nexus configuration, Cleanup Policies are the last missing piece.

**Comment by martincodes-de** [comment]
I wholeheartedly support the idea of integrating the Cleanup Policy API for Nexus.
 
It's long overdue and will provide significant advantages to our project. The ability to automatically clean up artifacts will enhance our build environments and ensure a more efficient development workflow.

I kindly ask the development team to consider prioritizing this feature for prompt implementation.

**Comment by eddiewebb** [comment]
We have Terraform driving full metal to meta provisioning and outside replacing the default admin credentials this is our only remaining manual task.   Thanks for any consideration towards this feature.

**Comment by RGPosadas** [comment]
+1, would greatly improve our QoL when configuring and maintaining nexus.

**Comment by mowhank** [comment]
+1, We fully configure our Nexus instance through Ansible and we can't manage add, update and delete cleanup policies while we manage blobstores, repositories, roles, users, ad with API.

Please take care of this request 👍

**Comment by Tosta-Mista** [comment]
+1 It would be great to have this, useful when you want to manage everything via scripts/ansible/terraform.

**Comment by danparisi** [comment]
Same for me, looking forward to have this feature

**Comment by sonykus** [comment]
Big Bump! Same as all the others above.

**Comment by mfld** [comment]
+1. Would love for this feature to be implemented

**Comment by fregatte** [comment]
Can't wait for it, it would be great to implement and give the ability to use in automated IaC configurations

**Comment by santimar** [comment]
@nblair any update on this?

**Comment by torsten-online** [comment]
Just from moving of own puppet deployment of Nexus, the missing management of cleanup Policies over the Rest Api is stopping us, to have Nexus fully into Code over Terraform.

I will really Welcome this, If sonatype will Take over this Feature, soon.

Thanks 👍

**Comment by soam247** [comment]
+1 would highly appreciate it

**Comment by Exether** [comment]
This is the last bit that prevents the full automation of Nexus deployment, thanks in advance !

**Comment by m4rii0** [comment]
Up, we cannot fully automate the configuration of the Nexus instance without this endpoints

**Comment by shook2012** [comment]
+1. Would love for this feature to be implemented

**Comment by BenjaminSchweizer** [comment]
+1 - would love it

**Comment by akramWewe** [comment]
+1

**Comment by tele-penguin** [comment]
+1 for these API features. Being able to fully configure via API would be extremely helpful.

**Comment by craigmiller160** [comment]
+1 for this

**Comment by stevehipwell** [comment]
It looks like this has been [released](https://help.sonatype.com/en/sonatype-nexus-repository-3-70-0-release-notes.html#create-and-manage-cleanup-policies-via-new-rest-api--pro-only-) but for pro users only.

@nblair could you please provide some context for why this isn't an OSS feature? The behaviour is already supported in OSS via the script API but as this is warned against a native API was requested. From the outside this looks like an arbitrary gating decision.

**Comment by mrprescott** [comment]
@stevehipwell Appreciate the question - to a certain extent, all OSS vs. Pro decisions are arbitrary, and we try to strike a balance between empowering devops practitioners and small teams with ensuring that the organizations deploying Repository at scale are contributing to the costs of making it possible.

In this case, this capability is closely aligned with deploying Repository under kubernetes, which is only safe to do with Repository Pro with an external PostgreSQL. Some time ago, we reviewed the root causes of a bunch of customer support tickets and found that running with an embedded database under kubernetes was a recipe for cumulative corruption and eventual catastrophic outage. We've seen this too many times, and it's why we deprecated our non-HA helm chart.

I think we have room to improve on awareness of this, we're currently looking at putting in-product warnings when an embedded deployment is under kubernetes.

**Comment by stevehipwell** [comment]
@mrprescott I've had success running a single replica Nexus3 OSS as a StatefulSet in Kubernetes with fully automated provisioning; so OrionDB on EBS volumes The only serious issue I encountered was self inflicted and caused by a monitoring failure while using the same volume for the blob store and DB (my instance pre dated S3 support); I did manage to fully recover this without resorting to a snapshot. All in all I've had a very positive experience.

So I think that as long as you understand the trade offs, OSS single replicas on Kubernetes solve a very common problem. I also think this pattern is a great way to introduce people to the power of Nexus. But without full provisioning support this path is going to be significantly less popular.

In my opinion, and please don't take this the wrong way, the main thing here is that the cleanup API doesn't seem distinct from the other APIs available in OSS, which makes it seem a little user hostile. But I do understand that you have a business to run, just some feedback.

**Comment by RGPosadas** [comment]
To add on to @stevehipwell 's comment, my team also runs Nexus3 OSS as a StatefulSet with as much automated provisioning as the OSS APIs allow. We as well mostly have positive experience with Nexus3. 

> In my opinion, and please don't take this the wrong way, the main thing here is that the cleanup API doesn't seem distinct from the other APIs available in OSS, which makes it seem a little user hostile. But I do understand that you have a business to run, just some feedback.

I respectfully agree and resonate with this comment.
