### ISSUE TITLE
Nexus OrientDB to Postgres migration - security realm and password auth problems

### ISSUE THREAD

**Issue by NickWemekamp** [sonatype/nexus-public#152]
Yesterday we finished the Nexus database migration but we ran into 2 bugs which we were able to resolve.

**Wrong password after migration**
in NEXUS_FOLDER/etc/fabric/nexus-store.properties the password field always has a trailing space " " after the migration. Resulting in Nexus not being able to start because the Postgres password is wrong. I had to manually remove the space after the password field and this solved this issue.

**Corrupted realm_configuration table after migration**
We upgraded Nexus 3.54.1 with nexus-db-migrator-3.54.1-01.jar and after the migration finished Nexus was not able to start and there was a Java stacktrace relating to the security realms (don't have the logs anymore). I was able to resolve this by manually editing the realm_configuration table as it had gotten corrupted after the migration (or already was corrupted before the migration but was still compatible with OrientDB). 

After the migration the row value was:
`1,"[""[NexusAuthenticatingRealm"", ""NexusAuthorizingRealm]""]"`
Which is not a valid JSON Array (it also had some Realm names missing)
I changed it manually back to
`["NexusAuthenticatingRealm", "NexusAuthorizingRealm"]`
and then Nexus did start with Postgres but I still had to manually enable some Security Realms again through the admin portal.

I did not have the realm problem on our testing environment but that was a 3.53 (?) migration with nexus-db-migrator 3.53.1-01.jar. Nexus is currently working so I don't have a problem right now.

**Comment by nblair** [comment]
Hi @NickWemekamp - migrating to PostgreSQL is a Pro only feature. As a pro customer, we would encourage you to please go to https://support.sonatype.com/ 

Let me know once you've started your journey there and I can close this ticket here.
