### ISSUE TITLE
Sync org.libvirt/libvirt

### ISSUE THREAD

**Issue by bgermann** [sonatype/nexus-public#157]
* What problem are you trying to solve?
Old version of libvirt in the central repository.

* Do you have a workaround you are using at present?
Using the version 0.5.3 from libvirt.org

* What feature or behavior is this required for?
The [Libvirt repos](https://mvnrepository.com/artifact/org.libvirt/libvirt?repo=libvirt)'s artifacts (at least the latest version 0.5.3 should be available in the central repository.

* How could we solve this issue? (Not knowing is okay!)
Syncing the repositories.

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Do not know.

* Anything else?
@K0zka This is a follow-up on [OSSRH-82206](https://issues.sonatype.org/browse/OSSRH-82206) which was wrongly marked as fixed.

**Comment by nblair** [comment]
Hi @bgermann - this project is specifically for filing issues with Sonatype Nexus Repository OSS. For help publishing artifacts to Maven Central, you should still use https://issues.sonatype.org/projects/MVNCENTRAL/summary.
