### ISSUE TITLE
NEXUS-31764 - proxy no longer working due to API changes?

### ISSUE THREAD

**Issue by ErikGrav** [sonatype/nexus-public#161]
Using: 3.36.0-01

I have been tracking possible progress on the old case: 
https://issues.sonatype.org/projects/NEXUS/issues/NEXUS-31764?filter=allissues

I cant see the issue there anymore so I just post here. 

Still having issues with the proxy,  what broke it, may perhaps be changes to the API of the target of the proxy

An example of the issue using telerik reporting. 17.0.23.118:

nexus fails with the following request (that previously worked.. but i dont seem to be able to configure it in the new manner required.. unless I am missing something im not aware of): 

`.nuget.internal.NugetFeedFetcher - Status code 404 contacting [https://nuget.telerik.com/v3/Packages(Id='telerik.reporting',Version='17.0.23.118')](https://nuget.telerik.com/v3/Packages(Id=%27telerik.reporting%27,Version=%2717.0.23.118%27))`

There has been changes to the target: 
`https://nuget.telerik.com/v3/search?q=Telerik.reporting`
gives a whole many options.. 

Such as: 
```
"@id": "[https://nuget.telerik.com/v3/registration/telerik.reporting/17.0.23.118.json"](https://nuget.telerik.com/v3/registration/telerik.reporting/17.0.23.118.json%22),

                    "version": "17.0.23.118",

                    "downloads": 0

```

This again points to> 
```
{
  "downloads": 0,
  "@id": "[https://nuget.telerik.com/v3/registration/telerik.reporting/17.0.23.118.json"](https://nuget.telerik.com/v3/registration/telerik.reporting/17.0.23.118.json%22),
  "@type": [
    "Package",
    "[http://schema.nuget.org/catalog#Permalink"](http://schema.nuget.org/catalog#Permalink%22)
  ],
  "listed": true,
  "packageContent": "[https://nuget.telerik.com/v3/package/telerik.reporting/17.0.23.118/telerik.reporting.17.0.23.118.nupkg"](https://nuget.telerik.com/v3/package/telerik.reporting/17.0.23.118/telerik.reporting.17.0.23.118.nupkg%22),
  "published": "2023-01-18T00:00:00+00:00",
  "registration": "[https://nuget.telerik.com/v3/registration/telerik.reporting/index.json"](https://nuget.telerik.com/v3/registration/telerik.reporting/index.json%22)
}
```
it seems like you have to search, find the correct url for downloading. 
Not just making a request with a packageid and version. 

I am not sure how i am to approach this change to how to request packages with the changes.. as sonatype attempts with a whole different format than what the API of telerik has these days. 
I seem to be able to search for the packages with the current config (old style of proxy) for the packages.. but im unable to download them due to fact that its trying with URLs that no longer exists. 

this is what sonatypenexus attempts to use to download the package:

`https://nuget.telerik.com/v3/Packages(Id='telerik.reporting',Version='17.0.23.118')`

This is what actually is the correct path to download it:

`https://nuget.telerik.com/v3/package/telerik.reporting/17.0.23.118/telerik.reporting.17.0.23.118.nupkg`

Having looked through the releases I have not seen any subjects that seem to address this issue.. 

Anyone know a workaround for this proxy issue? 

It may be that its already supported.. but I dont seem able to find any documentation of approaching this in this version or current version.

**Comment by nblair** [comment]
Thanks for open an issue @ErikGrav. I tried to setup a Nuget v3 proxy as you described in the latest version (3.55). While there is a similar exception in the logs, I noticed prior to that I get an authentication failure:

```
2023-06-13 14:26:40,102+0000 WARN  [qtp2139076772-1490]  admin com.sonatype.nexus.repository.nuget.datastore.internal.NugetProxyDispatcherFacet - Exception org.sonatype.nexus.repository.proxy.ProxyServiceException: HTTP/1.1 401 Unauthorized checking remote for update, proxy repo nuget-nuget.telerik.com-proxy-v3 failed to fetch https://nuget.telerik.com/v3/index.json with status line HTTP/1.1 401 Unauthorized, content not in cache.
2023-06-13 14:26:40,103+0000 WARN  [qtp2139076772-1490]  admin com.sonatype.nexus.repository.nuget.datastore.internal.NugetV3ProxyServiceIndexFacet - Failed to refresh service index on nuget-nuget.telerik.com-proxy-v3
org.sonatype.nexus.repository.proxy.ProxyServiceException: HTTP/1.1 401 Unauthorized
```

Pardon my naivete, as Nuget isn't a core competency of mine. This suggests that Telerik requires a (what looks to be paid) subscription in order to interact with this service. Is that correct?

**Comment by nblair** [comment]
I was able to gain credentials and configure the repository appropriately, and confirmed I am able to see the same error. I'll see what I can do to triage this further.

**Comment by ErikGrav** [comment]
Thank you @nblair .
Great to hear that you too manage to provoke the same error from the messy description. 
Let me know if there is anything more I can provide with or want me to test.

**Comment by ErikGrav** [comment]
hello @nblair , any news regarding this issue?

**Comment by ErikGrav** [comment]
Hello @nblair 
Any news to this case?

**Comment by nblair** [comment]
Hi @ErikGrav - this is in the queue still, but hasn't come up to the top yet to be assigned to a team. The error appears to be specific to this remote and not affecting our support for NuGet on the whole.

**Comment by ErikGrav** [comment]
Thank you for the update. 
Will watch for future releases.

**Comment by nblair** [comment]
Hi @ErikGrav - unfortunately, we've had to close this issue as Won't Fix. Telerik has made specific choices about how they implement NugetV3 support and as made intentional divergences that are not fully compatible with our Nuget V3 support. After reaching out to Telerik directly, they did not wish to partner on developing a joint fix.

**Comment by ErikGrav** [comment]
Hello, thanks for the update. 
It is a shame that telerik does not wish to partner to solve the issue. 
But from a business point of view I suppose its understandable from their side. 

Thank you for the time and trying @nblair, much appreciated.  

( time to find a 'hacky' way to do this through scripting ;) )
