### ISSUE TITLE
Unable to remove all roles of a user

### ISSUE THREAD

**Issue by zerint** [sonatype/nexus-public#162]
* What problem are you trying to solve?
Remove all roles of a user.
```
curl -X 'PUT' \
  '<nexus>/service/rest/v1/security/users/<could be anything>' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "userId": "<could be anything>",
  "firstName": "<could be anything>",
  "lastName": "<could be anything>",
  "emailAddress": "<could-be-anything>",
  "source": "<could be anything>",
  "status": "<could be anything>",
  "readOnly": <could be anything>,
  "roles": []
}'
```
```
400 Bad request
[
  {
    "id": "PARAMETER roles",
    "message": "must not be empty"
  }
]
```

* Do you have a workaround you are using at present?
Creating dummy roles that have close to no access to anything.
* What feature or behavior is this required for?
Nexus API
* How could we solve this issue? (Not knowing is okay!)
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
https://hub.docker.com/r/sonatype/nexus3/
Version: 3.47.1-01

**Comment by nblair** [comment]
Hi @zerint thanks for reporting an issue. The system requires that each user have at least one role, what is the use case for removing all roles? If the goal is to eliminate access for an account, as a workaround, could you create an empty role with no privileges?
