### ISSUE TITLE
Add support for SSHA 512 PasswordEncoder in LDAP connector

### ISSUE THREAD

**Issue by medley56** [sonatype/nexus-public#166]
* What problem are you trying to solve?
We are trying to use our LDAP system to provide SSO for Nexus. Our LDAP system uses SSHA 512 to hash user passwords and it seems that Nexus does not support the SSHA 512 hash algorithm. When a user logs in, we see the error message:
```
> Failed to connect to LDAP Server: Password encoding: SSHA512 has no associated PasswordEncoder.
> 2017-03-22 16:49:37,575+0100 INFO UNKNOWN org.sonatype.nexus.ldap.internal.connector.dao.password.DefaultPasswordEncoderManager - Verifying password with encoding: SSHA512 (encoder: null).
```
The user is provided an "Unknown Username/Password", which erroneously puts the blame on the user when the real problem is that Nexus can't negotiate with LDAP.

* Do you have a workaround you are using at present?
No. We are managing logins for Nexus manually and it is not a workable solution.

* What feature or behavior is this required for?
User log in.

* How could we solve this issue? (Not knowing is okay!)
Add support more secure and salted LDAP PasswordEncoders such as SHA 256, SHA 384, and SHA 512.

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Version 3.53.0-01
Running on the official Docker image.
Embedded H2 database.

* Anything else?
Please?

**Comment by nblair** [comment]
Hi @medley56 - my apologies in getting back to you, but support for SHA512 PasswordEncoders in the LDAP connector was delivered in on August 15th in version 3.59.0, please see [the release notes](https://help.sonatype.com/repomanager3/product-information/release-notes/2023-release-notes).
