### ISSUE TITLE
How to set "forceHardDelete" to blob?

### ISSUE THREAD

**Issue by zhucan** [sonatype/nexus-public#172]
Sonatype Nexus Repository OSS users can file an issue here.

Sonatype Nexus Repository Pro customers should not use this form - please go to https://support.sonatype.com to report issues.

Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* What problem are you trying to solve?
Hard delete for blob not soft delete

* Do you have a workaround you are using at present?
* What feature or behavior is this required for?
If the backend storage is s3, the soft delete only set tag to object, I want to hard delete for it
* How could we solve this issue? (Not knowing is okay!)
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
* Anything else?

**Comment by nblair** [comment]
Hi @zhucan - simply put, the only things in Nexus Repository that should hard delete a blob are the Compact Blobstore task (for file blobstores) and the bucket deletion policy (for S3). This design allows deployers to recover from accidentally deleted components. See https://help.sonatype.com/repomanager3/nexus-repository-administration/repository-management/configuring-blob-stores#ConfiguringBlobStores-AWSSimpleStorageService(S3) for more.

**Comment by zhucan** [comment]
@nblair if user can set the config  with "soft deletet". and "hard delete" is more suitable,  What do you think？
