### ISSUE TITLE
Name is null

### ISSUE THREAD

**Issue by neelared** [sonatype/nexus-public#173]
Hello Team,
we are using nexus 3.41.1 we can see below error on logs.

2023-06-19 14:18:03,629+0200 ERROR [qtp1686616688-101] user1 org.sonatype.nexus.extdirect.internal.ExtDirectExceptionHandler - Failed to invoke action method: coreui_User.read, java-method: org.sonatype.nexus.coreui.UserComponent.read
java.lang.NullPointerException: Name is null
at java.lang.Enum.valueOf(Enum.java:236)
at org.sonatype.nexus.security.user.UserStatus.valueOf(UserStatus.java:1)

But nexus seems to be functional from UI, even we can see red notification for “Name is null”

can you let us know what can be the issue here and how we can resolve this…

Thanks & Regards.

**Comment by nblair** [comment]
Hello @neelared - thanks for opening this issue. Your report doesn't have enough information for us to give you a precise answer. Is the user from a local source, LDAP, or Crowd? If externally sourced (LDAP or crowd), does the user have all of expected attributes set? What activity causes the log message? Have you upgraded to a more recent version?

**Comment by neelared** [comment]
Hello @nblair, Thank you for the response. Please find my inline comments.
Is the user from a local source, LDAP, or Crowd?---->LDAP
Does the user have all of expected attributes set?---> Yes, the user has all of expected attributes set.
What activity causes the log message?----> When we are trying to check the Local user on Nexus it has an empty list, tried to create a new user then also it gives this error **Name is Null**. 

Thanks & Regards,
Malleswar.

**Comment by nblair** [comment]
@neelared it seems like one or more of your local users is missing a required attribute. How that came to be is something that would be difficult to diagnose without a support engagement.
