### ISSUE TITLE
 Anonymous Access got vanished post restart of Nexus3 

### ISSUE THREAD

**Issue by neelared** [sonatype/nexus-public#174]
Hello All,
we are using Nexus3 version 3.41.1 for artifactory storage for my project. I have enabled Anonymous Access, in Incase Nexus got restarted Anonymous Access disabled the option automatically. Is there anything to set the option permanently?
Please let me know.

Thank you.
![c86cd7045dc8567a9533c5114fa7758aa38e372c_2_1035x711](https://github.com/sonatype/nexus-public/assets/103026094/401c6f65-5d7d-48b3-b2d0-f2f58a94cfac)

**Comment by neelared** [comment]
![Uploading c86cd7045dc8567a9533c5114fa7758aa38e372c_2_1035x711.png…]()

**Comment by mrprescott** [comment]
I just did a quick reproduce attempt on 3.56 and I'm not seeing it:
1. Start Repo 3.56 Pro single node backed by OrientDB
2. Log in as admin; navigate to Anon Access page
3. Observe that Anonymous mode is on
4. Turn Anonymous mode off
5. Restart Nexus
6. Refresh browser
7. Observe that anonymous mode is still off (as expected)
8. Turn Anonymous mode on
9. Restart Nexus
10. Refresh browser
11. Observe that anonymous mode is on (as expected)

Can you upgrade and reverify?
Is there anything noteworthy about your setup? (e.g. is it a Pro setup with a cluster? Do you have non-clustered Repo instances  behind a load balancer as part of a "Pool of Proxies" deployment?)

**Comment by nblair** [comment]
We cannot replicate the reported behavior on recent versions of Nexus Repository. #196 is similar looking report by [adviau](https://github.com/adviau) with the same version.
