### ISSUE TITLE
AdminPasswordFileManagerImplTest.testWriteFile_failure:92 Expected: is <false>      but: was <true>

### ISSUE THREAD

**Issue by ziwend** [sonatype/nexus-public#175]
* What problem are you trying to solve?
after ./mvnw clean install I got :

 T E S T S
-------------------------------------------------------
Running org.sonatype.nexus.security.authc.FirstSuccessfulModularRealAuthenticatorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.033 sec - in org.sonatype.nexus.security.authc.FirstSuccessfulModularRealAuthenticatorTest
Running org.sonatype.nexus.security.authc.AntiCsrfFilterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.987 sec - in org.sonatype.nexus.security.authc.AntiCsrfFilterTest
Running org.sonatype.nexus.security.authc.AuthenticatingRealmImplTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.218 sec - in org.sonatype.nexus.security.authc.AuthenticatingRealmImplTest
Running org.sonatype.nexus.security.authc.AntiCsrfHelperTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.067 sec - in org.sonatype.nexus.security.authc.AntiCsrfHelperTest
Running org.sonatype.nexus.security.PasswordHelperTest
Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.543 sec - in org.sonatype.nexus.security.PasswordHelperTest
Running org.sonatype.nexus.security.jwt.rest.JwtSecretApiResourceTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.73 sec - in org.sonatype.nexus.security.jwt.rest.JwtSecretApiResourceTest
Running org.sonatype.nexus.security.token.BearerTokenTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.04 sec - in org.sonatype.nexus.security.token.BearerTokenTest
Running org.sonatype.nexus.security.token.BearerTokenManagerTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.229 sec - in org.sonatype.nexus.security.token.BearerTokenManagerTest
Running org.sonatype.nexus.security.token.BearerTokenRealmTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.778 sec - in org.sonatype.nexus.security.token.BearerTokenRealmTest
Running org.sonatype.nexus.security.authz.AuthorizingRealmImplTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.561 sec - in org.sonatype.nexus.security.authz.AuthorizingRealmImplTest
Running org.sonatype.nexus.security.authz.CachingTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.472 sec - in org.sonatype.nexus.security.authz.CachingTest
Running org.sonatype.nexus.security.authz.WildcardPermission2Test
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec - in org.sonatype.nexus.security.authz.WildcardPermission2Test
Running org.sonatype.nexus.security.authz.AuthorizationManagerTest
Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.398 sec - in org.sonatype.nexus.security.authz.AuthorizationManagerTest
Running org.sonatype.nexus.security.authz.ExceptionCatchingModularRealmAuthorizerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in org.sonatype.nexus.security.authz.ExceptionCatchingModularRealmAuthorizerTest
Running org.sonatype.nexus.security.internal.RealmManagerImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.525 sec - in org.sonatype.nexus.security.internal.RealmManagerImplTest
Running org.sonatype.nexus.security.internal.PasswordValidatorTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in org.sonatype.nexus.security.internal.PasswordValidatorTest
Running org.sonatype.nexus.security.internal.DefaultSecurityPasswordServiceTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.139 sec - in org.sonatype.nexus.security.internal.DefaultSecurityPasswordServiceTest
Running org.sonatype.nexus.security.internal.AuthenticatingRealmImplTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.581 sec - in org.sonatype.nexus.security.internal.AuthenticatingRealmImplTest
Running org.sonatype.nexus.security.internal.RolePermissionResolverImplTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.163 sec - in org.sonatype.nexus.security.internal.RolePermissionResolverImplTest
Running org.sonatype.nexus.security.internal.SecurityApiImplTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.206 sec - in org.sonatype.nexus.security.internal.SecurityApiImplTest
Running org.sonatype.nexus.security.internal.rest.UserApiResourceTest
Tests run: 21, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.378 sec - in org.sonatype.nexus.security.internal.rest.UserApiResourceTest
Running org.sonatype.nexus.security.internal.AdminPasswordFileManagerImplTest
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.099 sec <<< FAILURE! - in org.sonatype.nexus.security.internal.AdminPasswordFileManagerImplTest
testWriteFile_failure(org.sonatype.nexus.security.internal.AdminPasswordFileManagerImplTest)  Time elapsed: 0.067 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <false>
     but: was <true>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.sonatype.nexus.security.internal.AdminPasswordFileManagerImplTest.testWriteFile_failure(AdminPasswordFileManagerImplTest.java:92)

Running org.sonatype.nexus.security.internal.SecurityConfigurationManagerImplTest
Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.586 sec - in org.sonatype.nexus.security.internal.SecurityConfigurationManagerImplTest
Running org.sonatype.nexus.security.internal.LegacyNexusPasswordServiceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.029 sec - in org.sonatype.nexus.security.internal.LegacyNexusPasswordServiceTest
Running org.sonatype.nexus.security.internal.DefaultSecuritySystemTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.563 sec - in org.sonatype.nexus.security.internal.DefaultSecuritySystemTest
Running org.sonatype.nexus.security.internal.UserManagerImplTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.454 sec - in org.sonatype.nexus.security.internal.UserManagerImplTest
Running org.sonatype.nexus.security.JwtHelperTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.512 sec - in org.sonatype.nexus.security.JwtHelperTest
Running org.sonatype.nexus.security.anonymous.AnonymousHelperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec - in org.sonatype.nexus.security.anonymous.AnonymousHelperTest
Running org.sonatype.nexus.security.anonymous.rest.AnonymousAccessApiResourceTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.402 sec - in org.sonatype.nexus.security.anonymous.rest.AnonymousAccessApiResourceTest
Running org.sonatype.nexus.security.role.ExternalRoleMappedTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.444 sec - in org.sonatype.nexus.security.role.ExternalRoleMappedTest
Running org.sonatype.nexus.security.role.EmptyRoleTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.2 sec - in org.sonatype.nexus.security.role.EmptyRoleTest
Running org.sonatype.nexus.security.role.RoleNotContainSelfValidatorTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.417 sec - in org.sonatype.nexus.security.role.RoleNotContainSelfValidatorTest
Running org.sonatype.nexus.security.role.RoleTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in org.sonatype.nexus.security.role.RoleTest
Running org.sonatype.nexus.security.role.rest.RoleApiResourceTest
Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.116 sec - in org.sonatype.nexus.security.role.rest.RoleApiResourceTest
Running org.sonatype.nexus.security.role.RolesExistValidatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec - in org.sonatype.nexus.security.role.RolesExistValidatorTest
Running org.sonatype.nexus.security.UserIdMdcHelperTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.018 sec - in org.sonatype.nexus.security.UserIdMdcHelperTest
Running org.sonatype.nexus.security.realm.OrderingRealmsTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.389 sec - in org.sonatype.nexus.security.realm.OrderingRealmsTest
Running org.sonatype.nexus.security.JwtFilterTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.304 sec - in org.sonatype.nexus.security.JwtFilterTest
Running org.sonatype.nexus.security.UserPrincipalsHelperTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.846 sec - in org.sonatype.nexus.security.UserPrincipalsHelperTest
Running org.sonatype.nexus.security.CookieFilterTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.571 sec - in org.sonatype.nexus.security.CookieFilterTest
Running org.sonatype.nexus.security.privilege.PrivilegeDescriptorSupportTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.014 sec - in org.sonatype.nexus.security.privilege.PrivilegeDescriptorSupportTest
Running org.sonatype.nexus.security.privilege.ApplicationPermissionTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec - in org.sonatype.nexus.security.privilege.ApplicationPermissionTest
Running org.sonatype.nexus.security.privilege.PrivilegesExistValidatorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.504 sec - in org.sonatype.nexus.security.privilege.PrivilegesExistValidatorTest
Running org.sonatype.nexus.security.privilege.rest.PrivilegeApiResourceTest
Tests run: 18, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.152 sec - in org.sonatype.nexus.security.privilege.rest.PrivilegeApiResourceTest
Running org.sonatype.nexus.security.user.MissingRoleUserManagerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.458 sec - in org.sonatype.nexus.security.user.MissingRoleUserManagerTest
Running org.sonatype.nexus.security.user.UserRoleMappingTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.772 sec - in org.sonatype.nexus.security.user.UserRoleMappingTest
Running org.sonatype.nexus.security.user.EmptyRoleManagementTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.057 sec - in org.sonatype.nexus.security.user.EmptyRoleManagementTest
Running org.sonatype.nexus.security.user.UserManagementTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.551 sec - in org.sonatype.nexus.security.user.UserManagementTest
Running org.sonatype.nexus.security.user.AdditionalRoleSecuritySystemTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.509 sec - in org.sonatype.nexus.security.user.AdditionalRoleSecuritySystemTest
Running org.sonatype.nexus.security.user.UserManagerTest
Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.182 sec - in org.sonatype.nexus.security.user.UserManagerTest
Running org.sonatype.nexus.security.user.UserManager2Test
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.211 sec - in org.sonatype.nexus.security.user.UserManager2Test
Running org.sonatype.nexus.security.UserIdHelperTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in org.sonatype.nexus.security.UserIdHelperTest
Running org.sonatype.nexus.security.config.MemorySecurityConfigurationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec - in org.sonatype.nexus.security.config.MemorySecurityConfigurationTest
Running org.sonatype.nexus.security.config.SecurityContributorTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.642 sec - in org.sonatype.nexus.security.config.SecurityContributorTest
Running org.sonatype.nexus.security.config.StaticSecurityConfigurationSourceTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.837 sec - in org.sonatype.nexus.security.config.StaticSecurityConfigurationSourceTest
Running org.sonatype.nexus.security.config.SecuritySettingsCleanerImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.02 sec - in org.sonatype.nexus.security.config.SecuritySettingsCleanerImplTest
Running org.sonatype.nexus.security.config.SecurityContributorThreadedTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.854 sec - in org.sonatype.nexus.security.config.SecurityContributorThreadedTest
Running org.apache.shiro.nexus.ShiroJCacheManagerAdapterTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.641 sec - in org.apache.shiro.nexus.ShiroJCacheManagerAdapterTest

Results :

Failed tests:
  AdminPasswordFileManagerImplTest.testWriteFile_failure:92
Expected: is <false>
     but: was <true>

Tests run: 301, Failures: 1, Errors: 0, Skipped: 0

* Do you have a workaround you are using at present?
* What feature or behavior is this required for?
* How could we solve this issue? (Not knowing is okay!)
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
org.sonatype.nexus:nexus-parent 3.56.0-01, ubuntu 22.04 
* Anything else?

**Comment by baseely** [comment]
This also fails while building on an IBM POWER `ppc64le` architecture machine.

**Comment by volkert-fastned** [comment]
I also encountered this issue on an ARM-based (Apple Silicon) Macbook Pro.

Could this be a platform-dependency issue in the test, since it also failed for @baseely on a PPC architecture?

Here is a Dockerfile to reproduce it:

```Dockerfile
FROM eclipse-temurin:17.0.14_7-jdk-noble AS builder

ARG NEXUS_PUBLIC_VERSION=3.77.2-02
ARG NEXUS_PUBLIC_DOWNLOAD_LINK=https://github.com/sonatype/nexus-public/archive/refs/tags/release-${NEXUS_PUBLIC_VERSION}.tar.gz
ARG NEXUS_PUBLIC_SHA256=4771298bacd71cd94d0ebdf9025adbb30a2a3b455994143d60aeeb368d3da072
ARG NEXUS_PUBLIC_TARGET_PATH=/Downloads/nexus-public-release-${NEXUS_PUBLIC_VERSION}.tar.gz

ADD --checksum=sha256:$NEXUS_PUBLIC_SHA256 $NEXUS_PUBLIC_DOWNLOAD_LINK $NEXUS_PUBLIC_TARGET_PATH

WORKDIR /src/nexus-public

RUN apt -y update \
    && apt -y install git \
    && apt clean \
    && tar xf "$NEXUS_PUBLIC_TARGET_PATH" --strip-components=1 \
    && ./mvnw clean install -Dpublic
```

I can't reopen this issue. I'll open a separate issue, since in my experience, comments to closed issues don't tend to be noticed by maintainers.

**Comment by volkert-fastned** [comment]
@nblair Can you maybe take another look into this failing test? I encountered this test failure with the [3.77.2-02 release](https://github.com/sonatype/nexus-public/releases/tag/release-3.77.2-02).

**Comment by volkert-fastned** [comment]
Issue #432 appears to be related to this, since it's about the exact same failing test.

**Comment by nblair** [comment]
I can't produce the test failure you are reporting. 

Looking at the source, this line provides an expectation: 

https://github.com/sonatype/nexus-public/blob/aec50e47d080933bc235f29e2669591343112a12/components/nexus-security/src/test/java/org/sonatype/nexus/security/internal/AdminPasswordFileManagerImplTest.java#L40

JUnit's TemporaryFolder expects to be able to create and write to files in the directory specified by the java.io.tmpdir System property. The error you are reporting suggests that the JVM running the unit test does not have the ability to create/modify files in that folder.

**Comment by nblair** [comment]
Hi @volkert-fastned, I can't replicate the unit test failure on development systems, but admittedly none of our development systems match the scenario you've constructed.

Let's look at the line preceding the unit test failure:

https://github.com/sonatype/nexus-public/blob/aec50e47d080933bc235f29e2669591343112a12/components/nexus-security/src/test/java/org/sonatype/nexus/security/internal/AdminPasswordFileManagerImplTest.java#L90

This unit test is confirming expected behavior from the AdminPasswordFileManagerImpl in the case where the deployer has incorrectly set file permissions on their sonatype-work directory.

Consulting the javadocs for the [File#setWritable](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/File.html#setWritable(boolean)) method:

> A convenience method to set the owner's write permission for this abstract pathname. **On some platforms it may be possible to start the Java virtual machine with special privileges that allow it to modify files that disallow write operations.**

Emphasis mine. I suspect the way you're running this container results in the underlying filesystem silently allowing this method to pass, but not actually removing the writable bit from the file. The next test has an assertion expecting an Exception to occur preventing a write, but since the volume under your container doesn't behave that way, the file write is allowed, breaking the assertion.

You'll need to consider an alternative way to build the software; one option might be to append `-DskipTests` to your `mvn install` command to bypass test execution, or to provide a filesystem under the workdir that correctly removes the writable bit from the temporary file created in that test.
