### ISSUE TITLE
Very slow job Delete Unused manifests and Images with s3 blob

### ISSUE THREAD

**Issue by Ardasher2012** [sonatype/nexus-public#176]
SHi. We use Sonatype Nexus Repository Manager OSS 3.37.3-02. Job ‘Delete Unused manifests and Images’ is incredibly slow with s3 blob. S3 storage is based on ceph. Ceph performance is good. Any idea?

**Comment by zhucan** [comment]
it's soft delete, after the time expire, the data will be deleted from backend storage. @Ardasher2012
