### ISSUE TITLE
sort parameter does not work in central.sonatype.com/solrsearch

### ISSUE THREAD

**Issue by joschua-gandert-valtech** [sonatype/nexus-public#181]
When you search via the Solrsearch API that is described here: https://central.sonatype.org/search/rest-api-guide/ the sort parameter seems to be ignored.

**Example:**

https://central.sonatype.com/solrsearch/select?q=g:org.apache.maven+AND+a:maven-plugin-api&core=gav&rows=10&wt=json&sort=v%20desc

We get version 3.1.1, then 2.0.3, then 3.6.1 and the newest version 4.0 is somewhere much lower.

We've tried this with many variations of the sort parameter (sort=version, sort=v, sort=timestamp..) and even some other ways to get the last version at the top of the JSON array (latest=version, version=latest)

Whatever we did, the order seems to stay the same, and thus the only way to get the latest version of a package is to load way more rows than is necessary, and even then we can never be sure.

**Comment by nblair** [comment]
This project is only for issues with Sonatype Nexus Repository. Please use https://issues.sonatype.org/projects/MVNCENTRAL for reporting issues with Maven Central - thanks!
