### ISSUE TITLE
Request permission to publish to sonatype

### ISSUE THREAD

**Issue by pnickoll** [sonatype/nexus-public#191]
Hi,

I have been routed here by following links from an old JIRA issue which was the same request for permission from someone else (https://issues.sonatype.org/browse/OSSRH-25089) 

As a member of the IBM WebSphere organization I require permissions to deploy to the following groupId:

net.wasdev.maven.tools.parents
net.wasdev.maven.tools.targets
net.wasdev.maven.tools.archetypes

**Comment by cbridgha** [comment]
I can vouch for Phil - He is part of the IBM org that controls these group id's

Thanks - Chuck

**Comment by mrprescott** [comment]
Hello @pnickoll, @cbridgha — this is actually the issue manager strictly for the self-managed Sonatype Nexus Repository solution. Apologies for the fine print, but if you look careflly at the banner warning on the old Jira, please continue to use it for OSSRH- or MVNCENTRAL-related issues.
