### ISSUE TITLE
unable to proxy rubygems.org escape

### ISSUE THREAD

**Issue by ns-rkusumoto** [sonatype/nexus-public#193]
* What problem are you trying to solve?

Pull escape gem from a proxy rubygems repo.

* Do you have a workaround you are using at present?

Pull directly from rubygems.org instead of using internal Nexus OSS.

* What feature or behavior is this required for?

Setup rubygems proxy repo to pull from rubygems.org.

* How could we solve this issue? (Not knowing is okay!)

Do not know.  Currently getting 500 responses from Nexus OSS when attempting to pull escape.
Browsing in Nexus shows this:
![escape](https://github.com/sonatype/nexus-public/assets/47642633/d56f98b5-836c-4ccd-b179-83e06df1ec8d)

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

Public docker image of OSS 3.57.0-01 
[sysinfo.json.txt](https://github.com/sonatype/nexus-public/files/12082661/sysinfo.json.txt)

**Comment by nblair** [comment]
Thanks for opening this issue @ns-rkusumoto - we are able to replicate a server error when attempting to proxy this same gem. We'll take a look!

**Comment by nblair** [comment]
Great news @ns-rkusumoto - we've found the root cause, and the bug has been fixed internally. We expect the changes to be available in our December release, 3.63.0. Thanks!
