### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by alalavin** [sonatype/nexus-public#194]
Hi,
we are using nexus, and we fac ed a problem. searching the net, we found the solution at this address
 https://issues.sonatype.org/browse/NEXUS-18036 but we cant access the link due to JIRA Policy,
please help!!

**Comment by nblair** [comment]
Hi @alalavin - it's hard to provide help without the questions posed in the new issue template. The more details you can provide the more likely the community can help.

**Comment by alalavin** [comment]
Hi, we checked a lot and found that the problem happened in orientdb record which was related to quartz-trigger job which might be harmed when it was doing a process and was open in ram. We did rebuild process in another orientdb and also replaced the config database files with a new nexus installed one but the problem didn't solve.
