### ISSUE TITLE
Allow creating response with a rich status code

### ISSUE THREAD

**Issue by iseki0** [sonatype/nexus-public#195]
Sonatype Nexus Repository OSS users can file an issue here.

Sonatype Nexus Repository Pro customers should not use this form - please go to https://support.sonatype.com to report issues.

Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* What problem are you trying to solve?
  Create response with a rich-status is difficult. 
* Do you have a workaround you are using at present?
  No, that's nexus wrong.
* What feature or behavior is this required for?
  Don't throw `NullPointerException`
* How could we solve this issue? (Not knowing is okay!)
  Merge the pull request. sonatype/nexus-public#98
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
  I guess... latest version? Looks the PR has no conflict

**Comment by nblair** [comment]
Thanks for opening an issue @iseki0 - we'll take a look at your contribution and see if it's something we can accommodate.

**Comment by iseki0** [comment]
@nblair Any updates? I don't think it's an enhancement, it's more like a bug.

**Comment by nblair** [comment]
Apologies for the delay. We appreciate your input, but we don't currently have a facility for accepting your contribution.

**Comment by iseki0** [comment]
@nblair OK, althought you can't accept my contribution... But it's a bug, you have to fix it.
