### ISSUE TITLE
Unable to stage artifacts

### ISSUE THREAD

**Issue by brettonw** [sonatype/nexus-public#202]
GOAL: push updated artifacts to maven central
PROBLEM: timeout? I can't effectively diagnose.
IMPACT: I cannot stage and post updated artifacts to maven central
DIAGNOSTIC:
Over the past 24 hours, Nexus staging is timing out on every build - and I don't see a way to get better information about whether I have a problem or if it is just a server load issue. Anecdotally, the release code didn't change between the last release (June) and now, but as an experiment I changed the deployment strategy to use `mvn clean deploy`. This resulted in a slightly different error - similar to the report for [OSSRH-58703](https://issues.sonatype.org/browse/OSSRH-58703):

```
[INFO]  * Closing staging repository with ID "usirdevbedrock-1013".

Waiting for operation to complete...
...........................................................................................Jul 26, 2023 10:18:30 AM com.sun.jersey.api.client.ClientResponse getEntity
SEVERE: A message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found
Jul 26, 2023 10:18:30 AM com.sun.jersey.api.client.ClientResponse getEntity
```
ACTION REQUESTED:
Some help diagnosing this problem would be appreciated, either as advice about some maven option to get more specific error, or how to check the staging status and server load, to see if I should just keep trying or wait for a better moment.

**Comment by brettonw** [comment]
Likewise, seems to have resolved. In the future, is there a way to see what's going on that causes this problem?

**Comment by bjornharvold** [comment]
I am seeing this too:

Maven output:
```
build	27-Jul-2023 16:25:45	Uploaded to ossrh: https://s01.oss.sonatype.org:443/service/local/staging/deployByRepositoryId/travelwink-1091/travel/wink/payment-sdk-java/28.2.0/payment-sdk-java-28.2.0-sources.jar (398 kB at 205 kB/s)
build	27-Jul-2023 16:25:45	[INFO]  * Upload of locally staged artifacts finished.
build	27-Jul-2023 16:25:45	[INFO]  * Closing staging repository with ID "travelwink-1091".
build	27-Jul-2023 16:25:46	
build	27-Jul-2023 16:25:46	Waiting for operation to complete...
build	27-Jul-2023 16:30:47	...................................................................................
build	27-Jul-2023 16:30:47	[WARNING] TIMEOUT after 301.3 s
build	27-Jul-2023 16:30:47	
build	27-Jul-2023 16:30:47	[ERROR] Rule failure while trying to close staging repository with ID "travelwink-1091".
build	27-Jul-2023 16:30:47	[ERROR] 
build	27-Jul-2023 16:30:47	[ERROR] Nexus Staging Rules Failure Report
build	27-Jul-2023 16:30:47	[ERROR] ==================================
build	27-Jul-2023 16:30:47	[ERROR] 
build	27-Jul-2023 16:30:47	[ERROR] 
build	27-Jul-2023 16:30:47	[ERROR] Cleaning up local stage directory after a Rule failure during close of staging repositories: []
build	27-Jul-2023 16:30:47	[ERROR]  * Deleting context 8f0a34c7c4ecfb.properties
build	27-Jul-2023 16:30:47	[ERROR] Cleaning up remote stage repositories after a Rule failure during close of staging repositories: []
build	27-Jul-2023 16:30:47	[ERROR]  * Not dropping failed staging repository with ID "travelwink-1091" (Rule failure during close of staging repositories: []).
build	27-Jul-2023 16:30:47	[ERROR] Remote staging finished with a failure: Staging rules failure!
```

No indication of which rules were broken and times out. This worked just fine during our last release. During the last release, we were first told that we had a 2rd party dependency vulnerability marked as HIGH. We fixed this and Sonatype Lift told us "Great job!" But, we were unable to release.

**Comment by nblair** [comment]
Hi @brettonw - thanks for opening this issue. This project is exclusively for support of Sonatype Nexus Repository. OSSRH support still goes through https://issues.sonatype.org/login.jsp. Please file a ticket there and they will be able to help.
