### ISSUE TITLE
Importing of dot-files 

### ISSUE THREAD

**Issue by kjellgren** [sonatype/nexus-public#208]
* What problem are you trying to solve?
I want to import iso from RHEL (rhel-9.2-x86_64-dvd.iso). I follow [the Repository Import Guide](https://help.sonatype.com/repomanager3/nexus-repository-administration/tasks/repository-import). My problem is that Nexus do not import file “/.treeinfo” (rpm-files are imported). This dot-file is in the root directory on the iso and without it the kickstart (anaconda) do not accept the url to Nexus.

* Do you have a workaround you are using at present?
None

* What feature or behavior is this required for?
Use Nexus repo when doing a kickstart (RHEL installation) of nodes.

* How could we solve this issue? (Not knowing is okay!)
Make import not skip the dot-file

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Sonatype Nexus RepositoryPRO 3.54.1-01, Ubuntu 22.04

**Comment by nblair** [comment]
Hi @kjellgren - Repository Import is a Pro-only feature. Would you mind opening this as a support ticket instead? That would provide the best path to resolution.

**Comment by kjellgren** [comment]
Support ticket is request #78040
