### ISSUE TITLE
About the problem that the file information has not changed after updating the file

### ISSUE THREAD

**Issue by czyczy1006** [sonatype/nexus-public#216]
Why is the file information returned after updating the file, and the returned md5 is still the file before the update, but the correct file information can be obtained by searching after about a second

**Comment by nblair** [comment]
Hi @czyczy1006  thanks for filing this, but we're not quite sure how to proceed. There isn't enough information to understand what might be going on.

**Comment by czyczy1006** [comment]
> Hi @czyczy1006 thanks for filing this, but we're not quite sure how to proceed. There isn't enough information to understand what might be going on.

I upload a file to a certain path, then modify the file and re-upload it to the same directory, then call the /service/rest/v1/search/assets interface, the md5 of the returned file is not the md5 of the latest uploaded file, but the previous one The md5 of the uploaded file, the md5 returned by re-query after about one second is correct
