### ISSUE TITLE
Containerd can bypass docker repository credential checks

### ISSUE THREAD

**Issue by osmanyozgatlioglu** [sonatype/nexus-public#217]
We're using Nexus OSS 3.56.0-01 on Rocky 9.
We have one docker group repository with one hosted and one proxy repo.
Docker pull commands needs login before as supposed to.
But containerd cli (v1.6.15-k3s1) can pull images directly, without proper credentials.
I suppose it shouldn't happen.

As far as I debugged, docker client first api call from repo;
`GET /v2/ HTTP/1.1'`
And get proper answer;
`HTTP/1.1 401 Unauthorized`

whereas containerd client directly asks for manifest file;
`HEAD /v2/afifisoftwareag/macroscanner/manifests/latest HTTP/1.1`
And got success at my case;
`HTTP/1.1 200 OK`
After that downloads image parts without credentials.

I checked open issues and latest change logs and can't find similar problem.

**Comment by nblair** [comment]
Hi @osmanyozgatlioglu thanks for opening an issue. Your report doesn't enough detail for us to replicate. My initial thought is that the behavior is most likely related to the access control configuration and the credentials your containerd client are using. Are you using anonymous access? Do you have a default role that grants wider access?

If you do in fact have a repeatable test case, I would kindly ask that you refrain from posting them here and instead responsibly disclose those details via our [Bug Bounty program](https://www.sonatype.com/report-a-security-vulnerability).

**Comment by mrprescott** [comment]
@osmanyozgatlioglu The Docker client and containerd take different approaches to authentication, which can interact in unexpected ways with anonymous mode. Can you confirm what your global "anonymous access" and repository-level "anonymous pull" settings are?

**Comment by osmanyozgatlioglu** [comment]
Hello,
Our default anonymous access is allowed. Repository level is not allowed.
I hope this helps.
Regards.
