### ISSUE TITLE
Visual Studio Browse of v3 Nuget feed with "Include prerelease" not working

### ISSUE THREAD

**Issue by jkrahn3** [sonatype/nexus-public#218]
* What problem are you trying to solve?
    - In Visual Studio, if you browse a hosted NuGet feed with the v3 URL (ending in index.json) and select "Include prerelease," no packages are shown. Even non-prerelease packages are not shown.
    - The behavior is the same in Visual Studio's Package Manager Console using the command `Find-Package -IncludePrerelease -Source mySource -AllVersions`
    - The behavior is also the same using Microsoft's Nuget Package Explorer app.
    - Using the nuget command line like `nuget list -Prerelease -Source mySource` or `nuget search -Prerelease -Source mySource` seems to work correctly in all versions I tested.
* Do you have a workaround you are using at present?
    - Typing in the Visual Studio search box seems to work
* What feature or behavior is this required for?
    - Browsing nuget packages in Visual Studio
* How could we solve this issue? (Not knowing is okay!)
    - If I knew, I would try to do it myself 😜
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
    - Nexus version: 3.39.0 and later. We have 3.38.1 but we want to take advantage of a bugfix in 3.43.0. 
    - Database: the default OrientDB one
    - OS: Windows 10
    - Visual Studio Professional 2019 Version 16.11.27 with Nuget 5.11.4

**Comment by mrprescott** [comment]
Thanks for filing this, @jkrahn3 — have you had a look at versions after 3.42? I do see in our internal Jira instance that we had an issue in 3.39 that was corrected shortly afterwards. Can you reproduce this with a more up-to-date version?

**Comment by jkrahn3** [comment]
Hi @mrprescott, currently reproducing in 3.58.1-02. I also spot checked versions in between based on what versions had Nuget items in the release notes, but I didn't track exactly which versions I tested. Everything from 3.39 on had the same behavior.

**Comment by nblair** [comment]
Hi @jkrahn3 - we were able to reproduce and remediate the issue. Keep an eye out for Release 3.66.0 next week which includes the changes. Thanks!
