### ISSUE TITLE
Q: not all scheduling tasks are visible

### ISSUE THREAD

**Issue by umialpha** [sonatype/nexus-public#226]
according to https://help.sonatype.com/repomanager3/nexus-repository-administration/tasks, there are many tasks.

I set up a test nexus public 3, version: 3.59.0-01, i am admin user, however, i cannot find many task, e.g. "repository.apt.rebuild.metadata"

<img width="655" alt="image" src="https://github.com/sonatype/nexus-public/assets/13465150/1ad261bc-b566-4b52-876e-7e68ffdb4812">

how does it be solved

**Comment by nblair** [comment]
Hi @umialpha - thanks for opening an issue. There are a number of tasks that do not show up in the Tasks UI as they do not have administrator controllable settings. These "invisible" tasks are run automatically by the application.
