### ISSUE TITLE
https://s01.oss.sonatype.org/#stagingRepositories "refresh" times out

### ISSUE THREAD

**Issue by soc** [sonatype/nexus-public#233]
Reproduction:

- Go to https://s01.oss.sonatype.org/#stagingRepositories, click "refresh".

What happens?

- It times out.¹

What should happen?

- It shouldn't time out.

---

¹
![timeout](https://github.com/sonatype/nexus-public/assets/42493/0c05629a-4060-41f5-955c-6b71b2759ace)

**Comment by buhaiovos** [comment]
Hello!
We are affected by this issue as well. Is there any information on when/how this could be resolved?
Thanks!

**Comment by sksamuel** [comment]
It's been happening for months for me, although last 2 days it has become unusable.

**Comment by buhaiovos** [comment]
> It's been happening for months for me, although last 2 days it has become unusable.

yup, I've also experienced this from time to time, but when I tried to access a staging repo today - it was and still is consistent with timeouts.

**Comment by soc** [comment]
I know it's a free service, no guarantees, no SLA etc.; but comparing the amount of papercuts inflicted while publishing code ... it's incredible what is seemingly acceptable in the Java world.

**Comment by buhaiovos** [comment]
Dunno, who is involved, but I've just managed to publish the artefact. I've noticed that there was a downtime for a couple of minutes - looked like a reboot. Thanks!

**Comment by nblair** [comment]
Hi @soc - this issue tracker is specifically for deployments of Nexus Repository OSS. Support for publishing to Maven Central can be found at https://issues.sonatype.org/projects/OSSRH/issues/. Thanks!
