### ISSUE TITLE
how in version 3.59 get NugetApiKey

### ISSUE THREAD

**Issue by alezander86** [sonatype/nexus-public#236]
hello guys, I used to be able to get a token using code but now in version 3.59, after updating I get this response when executing my script I checked the documentation and it was not updated What could be the problem? In your update, I read that you fixed some bug related to getting the NugetApiKey, could this have affected?

```
import groovy.json.*
import org.sonatype.nexus.security.authc.apikey.ApiKeyStore
import org.apache.shiro.subject.SimplePrincipalCollection

parsed_args = new JsonSlurper().parseText(args)

def getOrCreateNuGetApiKey(String userName) {
    realmName = "NexusAuthenticatingRealm"
    apiKeyDomain = "NuGetApiKey"
    principal = new SimplePrincipalCollection(userName, realmName)
    keyStore = container.lookup(ApiKeyStore.class.getName())
    apiKey = keyStore.getApiKey(apiKeyDomain, principal)
    if (apiKey == null) {
        apiKey = keyStore.createApiKey(apiKeyDomain, principal)
    }
    return apiKey.toString()
}

nuGetApiKey = getOrCreateNuGetApiKey(parsed_args.name)

return JsonOutput.toJson([
        nuGetApiKey: nuGetApiKey
])
```

`curl -v -u admin:admin123 -X POST -H 'Content-Type: text/plain' -d '{"name": "admin"}' \
 http://nexus:8081/service/rest/v1/script/test/run`

`"result" : `"{\"nuGetApiKey\":\"Optional[org.sonatype.nexus.internal.security.apikey.orient.OrientApiKey@44f96587]\"}"``

**Comment by nblair** [comment]
Hi @alezander86 - thanks for opening an issue. The method signature did change in 3.59 for the API you are calling, see https://github.com/sonatype/nexus-public/blob/dde318dce153f50b7d6c032b2d5b3e1d826626c1/components/nexus-security/src/main/java/org/sonatype/nexus/security/authc/apikey/ApiKeyStore.java#L57.
