### ISSUE TITLE
Issue : Cannot execute query "SELECT * FROM quartz_trigger WHERE state IN [ ?,?,? ]": low heap memory

### ISSUE THREAD

**Issue by Darknight123** [sonatype/nexus-public#238]
<html>
<body>
<p style="margin-top: 0px; color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Hi All,<br>we are using below nexu3 in production setup :</p><div class="md-table" style="overflow-y: auto; margin: 1em 0px; color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Version | 3.37.3-02
-- | --
Edition | OSS
Build Revision | 43b5a0e9e1ce21baf3f0ccbf7cb2811b6bbcf580

</div><p style="color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">We are getting below mentioned error very frequently post which even through the nexus becomes unavailable for end users:</p><p style="color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">“SELECT * FROM quartz_trigger WHERE state IN [ ?,?,? ]”: low heap memory<br>Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute query “SELECT * FROM quartz_trigger WHERE state IN [ ?,?,? ]”: low heap memory</p><p style="color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">we have below specification related to physical server and heap size -<br>physical memory 34G on NAME=“Red Hat Enterprise Linux Server”<br>VERSION=“7.9 (Maipo)”<br>-Xms10144m<br>-Xmx10144m<br>-XX:MaxDirectMemorySize=10G<br>-XX:+HeapDumpOnOutOfMemoryError<br>-XX:HeapDumpPath=…/sonatype-work/nexus3/log/hdump.hprof<br>-XX:+UnlockDiagnosticVMOptions<br>-XX:+LogVMOutput<br>-XX:LogFile=…/sonatype-work/nexus3/log/jvm.log<br>-XX:-OmitStackTraceInFastThrow<br>-Djava.net.preferIPv4Stack=true<br>-Dkaraf.home=.<br>-Dkaraf.base=.<br>-Dkaraf.etc=etc/karaf<br>-Djava.util.logging.config.file=etc/karaf/java.util.logging.properties<br>-Dkaraf.data=…/sonatype-work/nexus3<br>-Dkaraf.log=…/sonatype-work/nexus3/log<br>-Djava.io.tmpdir=…/sonatype-work/nexus3/tmp<br>-Dkaraf.startLocalConsole=false<br>-Djdk.tls.ephemeralDHKeySize=2048</p><p style="color: rgb(74, 74, 74); font-family: BlinkMacSystemFont, -apple-system, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, Cantarell, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 15.008px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">can someone let us know the possible reason as we have tried to increase the heap dump from 4 to 8 and now to 10 but still the issue persists.</p>
</body>
</html>

**Comment by mgfnv9** [comment]
Why this issue was closed ?
