### ISSUE TITLE
Not able to close and release the new version of the service

### ISSUE THREAD

**Issue by Prajwalgn-07** [sonatype/nexus-public#239]
Sonatype Nexus Repository OSS users can file an issue here.

Sonatype Nexus Repository Pro customers should not use this form - please go to https://support.sonatype.com to report issues.

If you believe you have found a security vulnerability, please use our [Bug Bounty Program](https://www.sonatype.com/report-a-security-vulnerability) to disclose responsibly.

Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* What problem are you trying to solve?
I am trying to deploy the `ekam-atoms` and `ekam-drivers` service new versions, but when I upload from local there are multiple instances of the same service getting reflected in staging repository, and If I choose any one of the repository then I am getting check sum error and signature invalidation error, and I have added my account details in my gradle.properties file, it was working fine 2 days back with same process. do help us out if anything is missed I have attached necessarysnapshots

* Do you have a workaround you are using at present?
* What feature or behavior is this required for?
It should successfully pass all the checks and release button should be enabled

* How could we solve this issue? (Not knowing is okay!)
No idea
* Tell us about your Nexus Repository deployment: What version, operating system, and database are you using?
We have a `build.gradle` , have attached a small piece of it, and we use `publishMavenJavaPublicationToMavenRepository` publishing task
```
repositories {
        maven {
            url "https://oss.sonatype.org/service/local/staging/deploy/maven2"
            credentials {
                username sonatypeUsername
                password sonatypePassword
            }
        }
    }
}
```
* Anything else?
<img width="1243" alt="Screenshot 2023-09-08 at 2 33 25 PM" src="https://github.com/sonatype/nexus-public/assets/85623711/71c73206-feb7-4c6a-9cdc-58fbbdcd314c">
<img width="1440" alt="Screenshot 2023-09-08 at 2 51 26 PM" src="https://github.com/sonatype/nexus-public/assets/85623711/ea09a845-b347-4883-ad37-d06c1b0d4e48">

**Comment by Prajwalgn-07** [comment]
@nblair any leads would be appreciated

**Comment by Prajwalgn-07** [comment]
Not sure how but now its working fine, will open it if I face the same issue again

**Comment by nblair** [comment]
Glad to here @Prajwalgn-07 - for reference, this is not the right place to report issues publishing. If you run into problems publishing to oss.sonatype.org, head to https://issues.sonatype.org/projects/OSSRH/issues to report an issue. Thanks!
