### ISSUE TITLE
docker login error | dial tcp [::1]:8095: connect: connection refused**

### ISSUE THREAD

**Issue by aayushave** [sonatype/nexus-public#242]
**Installations**:
- Windows docker desktop running on linux containers
- nexus repository Sonatype Nexus RepositoryOSS 3.60.0-02 

**What problem are you trying to solve?**
On Nexus Windows setup 
Created a docker hosted repository
with port 8095 which is available and with netstat listening confirmed.

when i try to login using docker login -u admin -p password http://localhost:8095
it throws error
**Error response from daemon: Get "http://localhost:8095/v2/": dial tcp [::1]:8095: connect: connection refused**

**What feature or behavior is this required for?**
* nexus repostory 

**How could we solve this issue? (Not knowing is okay!)**
* it should login, I am doing complete testing on windows setup

**Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?**

- OS windows11
- Windows docker desktop running on linux containers
- nexus repository Sonatype Nexus RepositoryOSS 3.60.0-02 

* Anything else?

**Comment by cheeeasy2501** [comment]
Same issue when i use https + ssl certificate
