### ISSUE TITLE
Nexus not acception android application bundle

### ISSUE THREAD

**Issue by stalldandelion** [sonatype/nexus-public#243]
When uploading and android application bundle with **strict content validation** checked we get an 400 error. This format is a valid bundle and Nexus should be able to handle it even with validation checked

**Errormessage:**
The requested URL returned error: 400 Detected content type [application/zip, application/x-zip-compressed], but expected [application/x-authorware-bin]: se/xxx/mimo/mimo-app/android/xxx/2.4.14-SNAPSHOT/app-2.4.14-SNAPSHOT.aab

**Comment by mrprescott** [comment]
Thanks for writing in, @stalldandelion. Clearly the mime type library doesn't know about .aab files. What I recommend is turning off strict content validation, that ought to allow you to publish the file.
