### ISSUE TITLE
Occacionally slow maven metadata generation in case of PostGress db

### ISSUE THREAD

**Issue by VladimirDe** [sonatype/nexus-public#245]
Scenario:
- nexus 3.46.0-01
- external PostGres db is used
- neither nexus nor postgre db server is exeriencing high load (neither RAM not CPU nor disk IOps)
- gradle is trying to get maven-metatdata.xml just after publication new version of maven artifact
- most of requsts are answered in a matter of milliseconds
- some of request are answered with delays > 30 seconds
- no other resource consuming services are running on servers (like antivirus)
- no nexus background tasks is runing in time of affected maven metadata acquiring

Typical answer:
```
*.*.*.* - ******* [18/Sep/2023:17:50:17 +0300] "GET /repository/*****-maven-****/com.acmecompany/maven-metadata.xml HTTP/1.0" 200 - 2400 3 "Gradle/6.8 (Linux;3.10.0-1160.90.1.el7.x86_64;amd64) (Oracle Corporation;1.8.0_351;25.351-b10)" [qtp1867149997-118580]
```
Problem request:
```
*.*.*.* - ******* [18/Sep/2023:17:53:23 +0300] "GET /repository/*****-maven-****/com.acmecompany/maven-metadata.xml HTTP/1.0" 200 - 2400 39876 "Gradle/6.8 (Linux;3.10.0-1160.90.1.el7.x86_64;amd64) (Oracle Corporation;1.8.0_351;25.351-b10)" [qtp1867149997-118580]
```
Tried to reproduce on latest version of nexus(3.58.1-02) - the same behaviour

Known workaround: use Gradle version 7 and above as it is acceptiong timeouts more than 30 seconds. Unfortunately yhis workaround could not be implemented in our case (legacy code)

**Comment by mrprescott** [comment]
@VladimirDe as a user of a Pro feature, your organization is entitled to support. Can you have one of your designated support contacts reach out via https://support.sonatype.com ?
