### ISSUE TITLE
Restore retain/keep only the last X versions

### ISSUE THREAD

**Issue by jzielke84** [sonatype/nexus-public#246]
To conserve disk space and improve performance (search / database related), users desire to have an equivalent task in Nexus 3 as the task in Nexus 2 called "Remove releases from Maven repository".

One criteria to select the components to delete was "retain only the last 5 release versions".

This issue is to track creating such a task.

I have copied this Issue from https://issues.sonatype.org/browse/NEXUS-10821 which dates back to 2016...

Since you're not able to access any of the old issues anymore, you can look up the old discussion here for references:
http://web.archive.org/web/20221007195526/https://issues.sonatype.org/browse/NEXUS-10821

**Comment by nblair** [comment]
Thanks for the suggestion @jzielke84. We have an upgrade to this idea already in flight and is planned to be delivered in a future release for our Pro customers.

**Comment by ksa-real** [comment]
So, this feature won't be released to non-paid users?

**Comment by jzielke84** [comment]
Seems so. This is ridiculous since this has been a feature in the free version of Nexus 2.

**Comment by nblair** [comment]
Hi @ksa-real and @jzielke84  - thanks for responding. The free feature in Nexus Repository Manager 2 is still available today, but we made a different decision with Nexus Repository 3. Repository 3 has a totally different architecture to support a much wider variety of software ecosystems, and advanced use cases like failover and high availability clustering. Our customers use v3 at scales that nexus v2 has never seen.  In a perfect world, we'd be able to give it all away for free, but all of the features (even the free ones) need significant investment to build and maintain and we fund that with features appropriate to larger organizations or teams that need support for dealing with scale.

With regards to when for @mide74: Nexus Repository Pro customers have early access to preview this capability in non-production deployments using the latest 3.62 release; we expect to make the capability Generally Available for Pro customers in Q1 2023.

**Comment by beppo-sturmtief** [comment]
In the hope someone reads this even while this has been closed (@nblair ): How about offering at least the minimum of a checkbox that will prevent the latest version of each artifact from being deleted for non-pro users? This is a substantial issue for OSS users and therefore the community...

**Comment by nblair** [comment]
That's a pretty good idea @beppo-sturmtief, would you mind opening that as
a separate issue? I'll label it so we can track it as a separate
enhancement and track demand for it.

**Comment by beppo-sturmtief** [comment]
Thanks! Done in #400
