### ISSUE TITLE
Too few warehouse types available

### ISSUE THREAD

**Issue by zouchengli** [sonatype/nexus-public#249]
Why does nexus built from this source code only have the types available in the screenshot below?
<img width="520" alt="image" src="https://github.com/sonatype/nexus-public/assets/27568522/63544274-e2a6-4dd3-920e-22d581ab561a">

**Comment by mrprescott** [comment]
@zouchengli those are the open source formats ('warehouse types'). The downloadable binary contains others which are free to use but not open source.
