### ISSUE TITLE
Nexus search API does not properly sort by version

### ISSUE THREAD

**Issue by edufresne** [sonatype/nexus-public#252]
**What problem are you trying to solve?**
I am currently doing the API call:
```
GET {{baseUrl}}/v1/search?sort=version&direction=desc&repository={{repo}}&maven.groupId={{groupId}}&maven.artifactId={{artifactId}}&maven.baseVersion=0.0.0.develop-SNAPSHOT&maven.extension=war
```
which worked for this purpose before but it now doesn't seem to be sorting properly on `sort=version`. The `version` sorting seems to do something as when it's not passed, the order changes. What isn't expected is that the data we get back in descending order for the `version` field is the following:
- `0.0.0.develop-20230919.133444-52`
- `0.0.0.develop-20230919.135739-53`
- `0.0.0.develop-20230919.135739-54`
- `0.0.0.develop-20230919.142303-59`
- `0.0.0.develop-20230919.141358-57`
- `0.0.0.develop-20230919.140440-55`
- ...
- `0.0.0.develop-20230919.174340-62`
- `0.0.0.develop-20230919.183432-64`
- ...
- `0.0.0.develop-20230905.133338-39`

The sorting doesn't seem to be working as you can see it's not alphanumerically sorted as the version number increases and then decreases. We then use `curl --follow-redirects .../search/assets/download` which then causes us to pull and deploy the wrong artifact because of the incorrect sorting.
 
**Do you have a workaround you are using at present?**
Nope

**What feature or behavior is this required for?**

I am trying to download a file from the latest Maven snapshot build from Nexus. The use case is for a Google App Engine deployment that requires us to download a raw WAR file published via Maven, unzip and then deploy the unpacked directory. Our CI/CD deploys our latest published artifact to our dev environment.

**How could we solve this issue?**
The sorting should act as expected. 

**Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?**
Sonatype Nexus Repository ManagerOSS 3.47.1-01 - Self hosted
OS: Ubuntu Linux

Thanks!

**Comment by nblair** [comment]
Thanks for opening an issue @edufresne. Are you able to replicate this behavior in the latest version?
