### ISSUE TITLE
Cleanup policy to support N last artifacts

### ISSUE THREAD

**Issue by Blefish** [sonatype/nexus-public#255]
* What problem are you trying to solve?

At current time, it is impossible to keep last N artifacts published as the only policies are based on component download and component upload time.
It would be beneficial to instead delete artifacts based on published date, excluding last N artifacts as some components do not need to be updated on a regular basis - perhaps even years. Current cleanup policies always remove these artifacts completely, unless it is republished periodically.

* Do you have a workaround you are using at present?

There are custom scripts that allow the behavior, for example https://stackoverflow.com/questions/69978245/setup-custom-cleanup-for-docker-images-in-nexus-repository

* What feature or behavior is this required for?

Repositories (docker, binary-raw and others)

* How could we solve this issue? (Not knowing is okay!)

There seems to be a ticket about this, but I cannot access it: https://issues.sonatype.org/browse/NEXUS-10821

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

[3.60.0-02 OSS embedded database with docker container

**Comment by nblair** [comment]
Thanks for the suggestion @Blefish. As mentioned in #246, we have an upgrade to this idea already in flight and is planned to be delivered in a future release for our Pro customers.
