### ISSUE TITLE
Upgrade path from 3.27.0 to latest

### ISSUE THREAD

**Issue by neha-live** [sonatype/nexus-public#257]
I am planning to upgrade nexus from 3.27.0 to latest version. Can we directly upgrade it to latest or first need to upgrade to intermediate version then to latest?

**Comment by nblair** [comment]
Thanks for opening an issue @neha-live. The product does support upgrading directly to the latest, although the wider the range of versions between upgrades the longer the upgrade process may take to apply any needed database schema updates and/or run follow up tasks.

Our best advice would be to test in a non-production environment first to get a sense of how it will perform for your dataset.
