### ISSUE TITLE
NEXUS-40345 Nexus 3.60.0 - jackson-core parsing limits

### ISSUE THREAD

**Issue by koldijan** [sonatype/nexus-public#258]
Last version Sonatype Nexus Repository 3.60.0 contains jar lib [jackson-core](https://github.com/FasterXML/jackson-core) in version 2.15. This is a problem of parsing String buffer limits, when we use Nexus npm-proxy for _@salesforce-ux/design-system_ 

Success Hot Fix: manualy use newer jar lib version jackson.core (example 2.15.2), please see: https://github.com/FasterXML/jackson-core#input-parsing-limits.

We would like to add a newer version of the library jakson-core to the new Nexus build, is it possible to check it this problem?

**Comment by nblair** [comment]
Thanks for opening an issue @koldijan. Is there something specific about that particular component that generates an error in your Nexus Repository deployment?

**Comment by koldijan** [comment]
No, Nexus is deployed on standalone virtual server, i think the problem is in the npm download meta for @salesforce-ux/design-system - they are too big (MBs) and the library jackson-core can't handle them because of the internal limit of buffer. Nexus then returns error:

`Failure servicing: GET /repository/npm-public/@
salesforce-ux%2Fdesign-system
com.fasterxml.jackson.core.exc.StreamConstraintsException: String length (5046272) exceeds the maximum length (5000000)
        at com.fasterxml.jackson.core.StreamReadConstraints.validateStringLength(StreamReadConstraints.java:290)`

**Comment by nblair** [comment]
Thanks @koldijan - having the error message and steps to replicate helps. We'll look into scheduling a jackson-core dependency update in a future release.
