### ISSUE TITLE
Unable to download snapshot

### ISSUE THREAD

**Issue by scottf** [sonatype/nexus-public#260]
* What problem are you trying to solve?
Published snapshot not downloadable by gradle

* Do you have a workaround you are using at present?
No

* What feature or behavior is this required for?
Building projects that use the library

* How could we solve this issue? (Not knowing is okay!)

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

My library has successfully been published:
https://s01.oss.sonatype.org/#view-repositories;snapshots~browsestorage~io/synadia/flink-connector-nats

https://s01.oss.sonatype.org/content/repositories/snapshots/io/synadia/flink-connector-nats/0.0.1-SNAPSHOT/

Using gradle I am getting this error:
> Could not resolve io.synadia:flink-connector-nats:0.0.1-SNAPSHOT

I read this:
https://central.sonatype.org/publish/publish-guide/#ossrh-usage-notes

My gradle setup specifies s01.oss.sonatype.org. Similar have worked for oss.sonatype.org

```
repositories {
    maven {
        url "https://s01.oss.sonatype.org/content/repositories/snapshots/"
    }
}

dependencies {
    implementation 'io.synadia:flink-connector-nats:0.0.1-SNAPSHOT'
}
```

**Comment by scottf** [comment]
JDK in gradle issue. Closing

**Comment by nblair** [comment]
Glad to hear you have it working. For future reference, this is not the right place for reporting issues publishing to Maven Central. For future issues like this, please use https://issues.sonatype.org/projects/OSSRH. Thanks!
