### ISSUE TITLE
include nexus.vmoptions in build created from the source

### ISSUE THREAD

**Issue by fbalicchia** [sonatype/nexus-public#274]
Hi

Is it possible that the package "nexus-base-template-<NEXUS_VERSION>.zip," which I have generated by compiling a specific tag and running successful unit tests, is different from the Nexus OS package that can be downloaded from "https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz"? 

With different I mean for example that in the generated package I was not able to find 
"${NEXUS_HOME}/bin/nexus.vmoptions" file.

Could you please point to the repo that generates the package present under path https://download.sonatype.com/nexus/3/nexus-${NEXUS_VERSION}-unix.tar.gz ?

Thanks for help

**Comment by mrprescott** [comment]
Yes, they are quite different. nexus-public is the open source core, but the pre-built binaries you can get from download.sonatype.com are a combined OSS and Pro install that enables or disables features based on the presence of a license file.
