### ISSUE TITLE
nexus installation failing due to missing recipe: apk-proxy

### ISSUE THREAD

**Issue by neha-live** [sonatype/nexus-public#275]
I am trying to install nexus 3.42 after taking backup of existing nexus instance. First, I took backup by running backup task in the nexus and then took in the longhorn. copied all the .bak files in the restore-from-backup directory to backup directory and removed security, component & config folder from db directory but it is still failing because of below error.

<html>
<body>

at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)
--
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.extender.NexusLifecycleManager.startComponent(NexusLifecycleManager.java:199)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.extender.NexusLifecycleManager.to(NexusLifecycleManager.java:111)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.extender.NexusContextListener.moveToPhase(NexusContextListener.java:319)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.extender.NexusContextListener.frameworkEvent(NexusContextListener.java:216)
Tue, Oct 17 2023 11:24:59 am | at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1597)
Tue, Oct 17 2023 11:24:59 am | at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
Tue, Oct 17 2023 11:24:59 am | at java.lang.Thread.run(Thread.java:750)
Tue, Oct 17 2023 11:24:59 am | 2023-10-17 00:24:59,066+0000 ERROR [FelixStartLevel] *SYSTEM Felix - Framework listener delivery error.
Tue, Oct 17 2023 11:24:59 am | java.lang.IllegalStateException: Missing recipe: apk-proxy
Tue, Oct 17 2023 11:24:59 am | at com.google.common.base.Preconditions.checkState(Preconditions.java:591)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.recipe(RepositoryManagerImpl.java:172)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.newRepository(RepositoryManagerImpl.java:192)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.restoreRepositories(RepositoryManagerImpl.java:284)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.repository.manager.internal.RepositoryManagerImpl.doStart(RepositoryManagerImpl.java:266)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.common.stateguard.StateGuardLifecycleSupport.start(StateGuardLifecycleSupport.java:69)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.common.stateguard.MethodInvocationAction.run(MethodInvocationAction.java:39)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.common.stateguard.StateGuard$TransitionImpl.run(StateGuard.java:193)
Tue, Oct 17 2023 11:24:59 am | at org.sonatype.nexus.common.stateguard.TransitionsInterceptor.invoke(TransitionsInterceptor.java:57)

</body>
</html>

**Comment by mrprescott** [comment]
The APK support is a community plugin that may have incompatibilities with 3.42 and/or other issues. We would normally need a support engagement to diagnose what's happening here.

**Comment by anonysoul** [comment]
The same issue occurred, but when I deleted the repository and plugin, the problem vanished.
