### ISSUE TITLE
Invocation API call security/roles (output all roles) on system with >10k roles leads to system unresponsive (hangs up)

### ISSUE THREAD

**Issue by VladimirDe** [sonatype/nexus-public#277]
* Invocation API security/roles (output all roles) on system with >10k roles leads to system irresponsible (hangs up)
* NO workaround exists
* Solution: to restart nexus service (t does not sound as solution)
* Version: 3.61.0-02 (latest)
* CPU: 16 cores, RAM: 16GB

**Comment by mrprescott** [comment]
We would not normally recommend this number of roles on a Repository OSS instance; it would be difficult to know what's going on at this scale without a support engagement. What are all these roles for, are you partitioning repositories with content selectors and/or making large numbers of repositories?

**Comment by VladimirDe** [comment]
Large numbers of repositories

**Comment by VladimirDe** [comment]
it seems you want to recommend me switch to Pro version (switch to external db) ?
