### ISSUE TITLE
Send repository report only when there are failures

### ISSUE THREAD

**Issue by ctapobep** [sonatype/nexus-public#279]
Currently I receive an email report on each deploy of the artifacts and get a lot of emails because of that. However if everything is successful, I don't really need the report. Unfortunately, at the moment there's only an option to unsubscribe fully. But I do want to see security vulnerability report if issues have been found.

**Comment by mrprescott** [comment]
@ctapobep Just to clarify, are you asking about a report generated by a Nexus Repository instance that your organization manages, or something else?

**Comment by mrprescott** [comment]
Okay, that makes sense. This issue tracker is for the open source core of Nexus Repository. If you have a question about or an issue with publishing open source artifacts to Maven Central, please use the OSSRH Issue Tracker at https://issues.sonatype.org/browse/OSSRH.
