### ISSUE TITLE
Stuck in `Operation in progress`

### ISSUE THREAD

**Issue by atkawa7** [sonatype/nexus-public#285]
Sonatype Nexus Repository OSS users can file an issue here.

Related issues 
https://issues.sonatype.org/browse/OSSRH-35112
https://issues.sonatype.org/browse/OSSRH-69919
iogithubatkawa7-1043

Sonatype Nexus Repository Pro customers should not use this form - please go to https://support.sonatype.com to report issues.

If you believe you have found a security vulnerability, please use our [Bug Bounty Program](https://www.sonatype.com/report-a-security-vulnerability) to disclose responsibly.

If you have a question about or an issue with publishing open source artifacts to Maven Central, please use the [OSSRH Issue Tracker](https://issues.sonatype.org/browse/OSSRH) instead.

Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* What problem are you trying to solve?
* Do you have a workaround you are using at present?
* What feature or behavior is this required for?
* How could we solve this issue? (Not knowing is okay!)
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
* Anything else?

**Comment by nblair** [comment]
This issue tracker is specifically for individuals running Nexus Repository OSS. The referenced issues you reported publishing to Maven Central are in the OSSRH Jira, which is the right place to get support for publishing to Maven Central.
