### ISSUE TITLE
proxy gcr private container registry doesn't work

### ISSUE THREAD

**Issue by qingbo-lu** [sonatype/nexus-public#292]
when trying to setup nexus as docker-proxy for gcr private registry, following this guide:
[ WARN  [qtp688832529-712] admin org.sonatype.nexus.repository.docker.internal.V2Handlers - Is the remote url a valid docker endpoint? Remote host https://eu.gcr.io/ with path /v2/ops-test/flink-jobs/manifests/1.0.0-rc.77 did not return the expected response. Error message: manifest unknown](https://support.sonatype.com/hc/en-us/articles/360054585854?_ga=2.21144827.172533779.1699940283-215175511.1699939711)

 WARN  [qtp688832529-712] admin org.sonatype.nexus.repository.docker.internal.V2Handlers - Is the remote url a valid docker endpoint? Remote host https://eu.gcr.io/ with path /v2/ops-test/flink-jobs/manifests/1.0.0-rc.77 did not return the expected response. Error message: manifest unknown

if config remote url with trailing gcloud project id, it failed either:
2023-11-15 08:54:30,588+0000 WARN  [qtp688832529-722] admin org.sonatype.nexus.repository.docker.internal.V2Handlers - Error: GET /v2/flink-jobs/manifests/1.0.0-rc.77: 400 - org.sonatype.nexus.repository.docker.internal.V2Exception$DigestInvalidByMismatch: provided digest did not match uploaded content

success with quay.io(private registry) docker-hub, gcr public registry.

**Comment by andy-clave** [comment]
Hello, are there any news here? Can someone explain how to setup proxy for private gcr, I have the same problem.

@qingbo-lu have you been able to fix the problem?

**Comment by qingbo-lu** [comment]
@andy-clave no, i switched to quay.io

**Comment by GiGurra** [comment]
Also having this issue. Nexus as proxy to private artifact registry (successor to gcr).
