### ISSUE TITLE
Unable to log in to https://s01.oss.sonatype.org/

### ISSUE THREAD

**Issue by kismet2399** [sonatype/nexus-public#298]
https://issues.sonatype.org/browse/OSSRH-97127 

has done , but I cannot login to  [https://s01.oss.sonatype.org/#welcome]

"Incorrect username, password or no permission to use the Nexus User Interface.
Try again.Forbidden"

![Snipaste_2023-12-02_13-42-50](https://github.com/sonatype/nexus-public/assets/34050223/408518c0-86c1-4adb-ad63-62f4ec3b9b4b)

I encounter the following error when publishing a JAR to the Maven repository.

 Failed to deploy artifacts: Could not transfer artifact io.github.kismet2399:operatelog:jar:sources:1.0.2-20231202.104138-1 from/to ossrh (https://s01.oss.sonatype.org/content/repositories/snapshots): Access denied to: https://s01.oss.sonatype.org/content/repositories/snapshots/io/github/kismet2399/operatelog/1.0.2-SNAPSHOT/operatelog-1.0.2-20231202.104138-1-sources.jar, ReasonPhrase: Forbidden.

**Comment by mpiggott** [comment]
Please see the Central docs for where to get help https://central.sonatype.org/pages/support/

**Comment by kismet2399** [comment]
Joel Orlina rebuild my permissions. Then it`s work.

https://issues.sonatype.org/browse/OSSRH-97185
