### ISSUE TITLE
Please give access for user olamy to deploy to groupId au.gov.amsa

### ISSUE THREAD

**Issue by olamy** [sonatype/nexus-public#319]
Actually it looks I'm lucky (or old enough :) ) to have the same uid for oss.sonatype.org and github.
So the mapping sounds easy.
I'd like to have access to upload to the groupId `au.gov.amsa`.

cc @davidmoten

**Comment by nblair** [comment]
Hi @olamy - this issue tracker is specifically for deployments of Nexus Repository OSS. Support for publishing to Maven Central can be found at https://issues.sonatype.org/projects/OSSRH/issues/. Thanks!

**Comment by olamy** [comment]
Hi @nblair 
Ah ok but the banner says this will be deprecated :) https://issues.sonatype.org/projects/OSSRH/issues/
So the process now is to send an email?

**Comment by nblair** [comment]
Per https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/ it depends on your request:

> Registration and Namespace Requests[(https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via [central.sonatype.com](https://central.sonatype.com/). We have [additional documentation](https://central.sonatype.org/register/central-portal/) on the process of signing up and requesting namespaces.

> Support Requests(https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our central-support@sonatype.com email. We will continue to provide the same level of responsiveness and helpfulness, just via a different medium.

**Comment by olamy** [comment]
Thanks,
So if I understand correctly this particular request should go to central-support@sonatype.com?
