### ISSUE TITLE
Namespace Approval via TXT are not working

### ISSUE THREAD

**Issue by myappfree** [sonatype/nexus-public#320]
Hello, 
i've added the namespaces
maf.ad 
mychips.io

We also added the TXT record on our domain but the system keep fail verification.

It's also uncler the namespace standard in this case:
ususally the format is org.sonatype.nexus
but web domain have different format : nexus.sonatype.org

Could you please clarify?

**Comment by nblair** [comment]
Hi @myappfree - this issue tracker is specifically for deployments of Nexus Repository OSS. Support for publishing to Maven Central can be found at https://issues.sonatype.org/projects/OSSRH/issues/. Thanks!
