### ISSUE TITLE
release notes links not working anymore

### ISSUE THREAD

**Issue by mendorf** [sonatype/nexus-public#334]
* What problem are you trying to solve?
   Access the release note links present in the 2024 releases
   
* Do you have a workaround you are using at present?
  directly access the release notes through https://help.sonatype.com/en/release-notes.html
  
* What feature or behavior is this required for?
  assessing change impact on updates
  
* How could we solve this issue? (Not knowing is okay!)
  idk, but probably there is some recent change in how content is organized on help.sonatype.com and the release jobs need to be modified to adapt to the new organization logic; or there is an issue with help.sonatype.com
  
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
  this is not specific to my deployment, so I will leave this unanswered.
  
* Anything else?
  Sunshine comes after the rain.

**Comment by nblair** [comment]
Hi @mendorf thanks for opening an issue. I'm able to access https://help.sonatype.com/en/release-notes.html without issue. Can you clarify what you are seeing?

We did move our help documentation to a new platform recently. We've moved all of the redirects we're aware of but if there is a stray link out there we could use your help.

**Comment by mendorf** [comment]
Hi @nblair, I am sorry I forgot to update here:
I asked at docs@sonatype.com and the team provided these replies few days ago:

> We now have a redirect in place so that https://help.sonatype.com/repomanager3/product-information/release-notes/2024-release-notes/sonatype-nexus-repository-3.64.0-release-notes will lead to the correct place.

> Thanks for reporting this broken link, Thomas.  You should find we have added a redirect to the correct location in the docs.  We will look to update this auto-release process to include the correct links going forward.
> 
> https://help.sonatype.com/en/sonatype-nexus-repository-3-64-0-release-notes.html

Feel free to close, if you think that the implemented redirect is working for future releases as well (e.g. I came across https://github.com/sonatype/nexus-public/releases/tag/release-3.64.0-04 where the link to the release notes was not working, but now it does, as well as for the past releases).

**Comment by nblair** [comment]
Ah good catch. I've updated the internal docs for our release process to make sure that when we add the next release tag it uses the URL format of our new help platform. Thanks!
