### ISSUE TITLE
previous user name on https://oss.sonatype.org/ has not been transfered to the https://central.sonatype.org/

### ISSUE THREAD

**Issue by jianlins** [sonatype/nexus-public#336]
In the old server, I had been approved to use the namespace 'edu.utah.bmi.' However, after registering on the new server using the same email, I noticed that this namespace was not attached to my account. When I attempt to add the 'edu.utah.bmi' namespace, I receive an error message stating, 'Namespace 'edu.utah.bmi' is already registered as an OSSRH Namespace.' The link provided in the error message is not helpful.

I also tried signing up using Google authentication with the same email, but this did not resolve the issue.

I would appreciate any guidance on this matter.

**Comment by nblair** [comment]
This issue tracker is specifically for deployments of Nexus Repository OSS. 
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com. 

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our central-support@sonatype.com email.
