### ISSUE TITLE
How can remove "repository" virtual directory for each repository URL

### ISSUE THREAD

**Issue by mohjam2004** [sonatype/nexus-public#339]
Hi,
I use nexus3,
for each repository that I create, a virtual directory "repository" is added after repo_ip:port.
for example for my rhel8 rpm repository the url will be : **repo_ip:port/repository/rhel8**
Is there any way that I can remove "repository" virtual directory for each repo url that I want to create.
In my example I want the url to be: **repo_ip:port/rhel8**

**Comment by mrprescott** [comment]
@mohjam2004 There's nothing built into Repository that would let you do this, but you could experiment with using a reverse proxy to map the URLs. However, you may run into the issue with certain formats (e.g. npm) that the index metadata has absolute URLs in it, which will be incorrect and therefore break many use cases.
