### ISSUE TITLE
Unable to select Project on Central Statistics 

### ISSUE THREAD

**Issue by avlemos** [sonatype/nexus-public#345]
* What problem are you trying to solve?
I'm trying to check the statistics for com.itextpdf with my username alemos

* Do you have a workaround you are using at present?
I do not

* What feature or behavior is this required for?
Check Central statistics for an opensource project

* How could we solve this issue? (Not knowing is okay!)
I get two 400s, one 503 and one 404 when opening https://oss.sonatype.org/#central-stat

**Comment by avlemos** [comment]
400:

- https://oss.sonatype.org/service/local/outreach/links?_dc=1708605354717
- https://oss.sonatype.org/service/local/outreach/status?_dc=1708605355001

404:
- https://oss.sonatype.org/service/local/lvo/nexus-pro/2.15.1-02?_dc=1708605354726

503:
- https://oss.sonatype.org/service/local/stats/projects?_dc=1708605354733

**Comment by nblair** [comment]
Hi @avlemos unfortunately this isn't the right place to get the help you need.

This issue tracker is specifically for deployments of Nexus Repository OSS.
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.
