### ISSUE TITLE
Feature: content selector parameter for group repository

### ISSUE THREAD

**Issue by Zetanova** [sonatype/nexus-public#351]
* What problem are you trying to solve?
Limit access to a hosted nuget repository provided over a group repository.
Currently it is not possible to limit access on a single group member 
and to allow everything on an other member, 
like a cache proxy repository.

* Do you have a workaround you are using at present?
Not to using the group repository feature

* What feature or behavior is this required for?
To provider a group nuget repository to provider access to proxy nuget.org and a hosted nuget repository at the same time.

* How could we solve this issue? (Not knowing is okay!)
Add a parameter specific to the  a group repository to the [content selector ](https://help.sonatype.com/en/content-selectors.html)
beside `path` and `format` example: `repo` or `member`

Example selector:
```
member == 'nuget-proxy' or (path =^ "/MyPrefix")
```

 
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
container, OSS 3.65.0-02

**Comment by mrprescott** [comment]
@Zetanova Can you add a bit more context about why you need this? You want a group that contains a proxy (along with other repositories), but _some users_ are forbidden from resolving components in the proxy, while others are not? Any texture you can provide about how the situation came about would be useful.

**Comment by Zetanova** [comment]
In reverse, In the group repository is a single private nuget repository where some some users can't access all packages 
and a proxy repository to the public nuget repo

I played around and found now a workaround for my use case
`path =^ "/MyPrefix" or path =^ "/v3/"` 

This will allow access only to `MyPrefix*`packages and to all packages in the public nuget.org repository.

**Comment by mrprescott** [comment]
Very good, that's really the intended use. Permission are all positive, so (unfortunately) if you have an "everything but these things" requirement, it can involve a bit of noodling to figure out how to cleanly express that.
