### ISSUE TITLE
No able to see artifacts in staging repositoy

### ISSUE THREAD

**Issue by ankit-patil-hubs** [sonatype/nexus-public#352]
About 2 weeks ago my team published an artifact and we got the below message, but we cannot see this new artifact under the staging repository in Nexus, is this an issue? or are we looking in the wrong place, or is it removed because it was 2 weeks old?

```
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/14.0.0/dct-api-14.0.0.jar (2.1 MB at 108 kB/s)
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/14.0.0/dct-api-14.0.0.pom
Progress (1): 4.1/11 kB
Progress (1): 8.2/11 kB
Progress (1): 11 kB    
                   
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/14.0.0/dct-api-14.0.0.pom (11 kB at 133 kB/s)
Downloading from ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/maven-metadata.xml
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/maven-metadata.xml
Progress (1): 300 B
                   
Uploaded to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/maven-metadata.xml (300 B at 3.6 kB/s)
Uploading to ossrh: https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/com/delphix/dct-api/14.0.0/dct-api-14.0.0-tests.jar
```

**Comment by nblair** [comment]
Hi @ankit-patil-hubs unfortunately this isn't the right place to get the help you need.

This issue tracker is specifically for deployments of Nexus Repository OSS.
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.
