### ISSUE TITLE
I need to raise ticket to jira , how? regrading open source project repository hosting

### ISSUE THREAD

**Issue by happyusha** [sonatype/nexus-public#355]
Sonatype Nexus Repository OSS users can file an issue here.

Sonatype Nexus Repository Pro customers should not use this form - please go to https://support.sonatype.com to report issues.

If you believe you have found a security vulnerability, please use our [Bug Bounty Program](https://www.sonatype.com/report-a-security-vulnerability) to disclose responsibly.

If you have a question about or an issue with publishing open source artifacts to Maven Central, please use the [OSSRH Issue Tracker](https://issues.sonatype.org/browse/OSSRH) instead.

Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* What problem are you trying to solve?
* Do you have a workaround you are using at present?
* What feature or behavior is this required for?
* How could we solve this issue? (Not knowing is okay!)
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
* Anything else?

**Comment by nblair** [comment]
Hi @happyusha unfortunately this isn't the right place to get the help you need.

This issue tracker is specifically for deployments of Nexus Repository OSS.
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.
