### ISSUE TITLE
No Health Check capability on Maven Proxy

### ISSUE THREAD

**Issue by robross0606** [sonatype/nexus-public#356]
We have several different repository types on our server (npm, helm, docker, pypi, etc.).  We also have a maven proxy set up pointing at Maven Central just as described in Nexus documentation.  However, I noticed that there is no option for [Repository Health Check](https://help.sonatype.com/en/repository-health-check.html) on that proxy even though the documentation also says this should be available. 

![image](https://github.com/sonatype/nexus-public/assets/2965467/22d295fb-ea59-4149-9f73-9a328cba8589)
![310913683-fb133897-3e0a-49ac-bff7-768768de1769](https://github.com/sonatype/nexus-public/assets/2965467/721469fd-5615-479b-bf5b-17c16a461963)

Unlike our other repo types, there is no corresponding Task set up for Maven, and no "Health Check" data for this proxy.

![image](https://github.com/sonatype/nexus-public/assets/2965467/69280adb-76eb-4b50-8c93-882a49f8a0a5)
![image](https://github.com/sonatype/nexus-public/assets/2965467/d29d6eb8-0355-4148-886f-426f4a3d4c95)

I tried creating a new test Maven proxy repository and the same problem occurred.

**Comment by nblair** [comment]
That's curious @robross0606 - I'm unable to replicate on the latest release (3.66.0); are you able to upgrade and still see the same behavior? I don't see anything in the backlog for that version, I would suggest upgrading and inspecting your logs to see if anything is reported.

**Comment by robross0606** [comment]
I have inspected the logs but don't see anything of note in there about it.  Is there one particular log I should be focusing on?

**Comment by m4rii0** [comment]
I can reproduce this issue on version `OSS 3.63.0-01`

Maven proxy repositories created from the API (using a terraform provider) **do not have** the button to enable repository healthchecks while the same type of repository created from the UI does have this button.

cc/ @nblair @robross0606

**Comment by robross0606** [comment]
I'm creating them from the UI.  We have never created a repository from the API.

**Comment by m4rii0** [comment]
After doing more tests, I checked that repositories with **mixed** value in the "Version Policy" field do not have that button enabled, which matches the @robross0606 screenshot as well.

cc/ @nblair

**Comment by nblair** [comment]
Ah - good catch, the repository health check does not support the Mixed Version Policy type, you have to use Releases Version Policy only.
