### ISSUE TITLE
The open address has been stuck in Initializing

### ISSUE THREAD

**Issue by lanzhenkai** [sonatype/nexus-public#365]
When I cloned the source code, followed the steps to build and run successfully,
Build and run steps:
`./mvnw clean install -DskipTests `
`unzip -d target assemblies/nexus-base-template/target/nexus-base-template-*.zip `
`./target/nexus-base-template-*/bin/nexus console`

However, the page was still stuck in Initializing, and an error was reported when the browser was opened to debug.

react-dom.production.min.js:216 TypeError: Cannot read properties of undefined (reading 'filter')
at UsageMetricsAlert (UsageMetricsAlert.jsx:55:42)

The reason is something like '@sonatype/nexus-ui-plugin'; It's not built into the app
![未命名1711015322](https://github.com/sonatype/nexus-public/assets/12442254/4971ee9a-4742-4b6c-a00c-b571613bb12c)
![未命名1711015346](https://github.com/sonatype/nexus-public/assets/12442254/f6767d73-16da-4d74-83a6-cdf4640e808e)

**Comment by nblair** [comment]
Thanks for opening this @lanzhenkai - this repository is simply a mirror of just the open source assets included in Sonatype Nexus Repository. If you are building from the default branch of this repository, you are only getting a weekly export of the latest code in development, there's no guarantee of the state it's in.

We'd encourage you to run our official builds instead available from https://help.sonatype.com/en/download.html.
