### ISSUE TITLE
nexus-staging-maven-plugin ignores "maven.deploy.skip" in a submodule

### ISSUE THREAD

**Issue by andrus** [sonatype/nexus-public#367]
Using `nexus-staging-maven-plugin:1.6.13` in the [DFLib DataFrame project](https://github.com/dflib/dflib). It is a multi-module maven project, and I would like one of the child modules (`dflib-benchmark`) to be skipped during deployments. In the past I used to be able to do that using properties from `maven-deploy-plugin`:
```xml
<maven.deploy.skip>true</maven.deploy.skip>
```

Unfortunately, it doesn't seem to work in this project, and `dflib-benchmark` jars are published (as both [snapshots](https://s01.oss.sonatype.org/content/repositories/snapshots/org/dflib/dflib-benchmark/1.0.0-SNAPSHOT/) and releases). Instead of the property, I tried explicitly configuring `maven-deploy-plugin` with no luck.

So is this expected to work, or is there a different way to skip individual modules?

## Parent pom.xml

from https://github.com/dflib/dflib/blob/main/pom.xml 
```xml
<plugin>
    <groupId>org.sonatype.plugins</groupId>
    <artifactId>nexus-staging-maven-plugin</artifactId>
    <extensions>true</extensions>
    <configuration>
        <serverId>oss-sonatype-releases</serverId>
        <nexusUrl>https://s01.oss.sonatype.org/</nexusUrl>
        <autoReleaseAfterClose>false</autoReleaseAfterClose>
    </configuration>
</plugin>
```

## pom.xml of the module we want to skip

from https://github.com/dflib/dflib/blob/main/dflib-benchmark/pom.xml 
```xml
<properties>
    <maven.deploy.skip>true</maven.deploy.skip>
</properties>
```

**Comment by nblair** [comment]
Hi @andrus - it looks like you are trying to publish to Maven Central. Sonatype has recently posted instructions on the new way to publish, check out https://central.sonatype.org/register/central-portal/. As I understand, the use of the old staging plugin you reference here is being phased out.

This issue tracker is for a different purpose, specifically for deployments of Nexus Repository OSS.
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/), there are two ways for Maven Central publishers to get support:

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.

**Comment by andrus** [comment]
This is not about publishing to Maven Central per se. It about an issue with the Sonatype-maintained Maven plugin - `nexus-staging-maven-plugin` (so specific software, not a pubishing target). I can't find a GitHub repo for it to post an issue there. I will try central-support@sonatype.com unless there's a better place?

**Comment by lxp135** [comment]
use excludeArtifacts
```

<plugin>
    <groupId>org.sonatype.central</groupId>
    <artifactId>central-publishing-maven-plugin</artifactId>
    <version>0.4.0</version>
    <extensions>true</extensions>
    <configuration>
        <publishingServerId>minioplus</publishingServerId>
        <tokenAuth>true</tokenAuth>
        <excludeArtifacts>
            <artifact>minio-plus-application</artifact>
            <artifact>minio-plus-application-mysql</artifact>
        </excludeArtifacts>
    </configuration>
</plugin>
```
