### ISSUE TITLE
OSchemaNotCreatedException: Schema is not created and cannot be loaded

### ISSUE THREAD

**Issue by gmitch215** [sonatype/nexus-public#388]
* What problem are you trying to solve?
Trying to set it up on my VPS by following [this guide](https://blog.sonatype.com/how-to-get-started-with-sonatype-nexus-repository-manager-oss) and I get this error:
![image](https://github.com/sonatype/nexus-public/assets/54124162/940e4e6c-cbf8-4b27-a1f8-60fd7a58e859)

* Do you have a workaround you are using at present?
Believe it is a bug, so no

* What feature or behavior is this required for?
Trying to set it up

* How could we solve this issue? (Not knowing is okay!)
Figure out if I'm doing something wrong or if this is a bug

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Using Nexus v3.67.1 for Linux

* Anything else?
3GB RAM, 1 CPU, command is `./nexus run -Xms2G -Xmx2G`, using OpenJDK 8

**Comment by nblair** [comment]
Hi @gmitch215 thanks for opening an issue. It's not clear enough from your screenshot the full details of the error message. OrientDB has proven to be unreliable, it's not uncommon for lurking database corruption to appear suddenly or after an upgrade.
Do you have a backup to restore from? Our ability to diagnose/troubleshoot is limited. With a Pro license, that would entitle you to support with our experts.

**Comment by gmitch215** [comment]
I'm setting it up, there isn't any data that needs to be recovered. Something might've gotten corrupted on initial startup. Is there something I need to delete?

**Comment by nblair** [comment]
The OrientDB database is available under the sonatype-work/nexus3/db directory. If you delete that whole directory it will restart from scratch; trying to do something surgical would be immensely time consuming at this point. I would urge if you are starting from scratch to use the latest available version; https://help.sonatype.com/en/download.html is the main page, 3.68.0 is May's release and is rolling out now.

**Comment by gmitch215** [comment]
This worked. Thank you!
