### ISSUE TITLE
Authentification to Azure Container Registry / azurecr.io does not work as it should

### ISSUE THREAD

**Issue by marcohald** [sonatype/nexus-public#393]
* What problem are you trying to solve?
Create a Docker Proxy for a private Azure Container Registry which needs basic auth
* Do you have a workaround you are using at present?
No
* What feature or behavior is this required for?
A working authentification like the Docker Client
* How could we solve this issue? (Not knowing is okay!)
As far as I have seen, the difference between the Auth Request from Nexus and the Docker Client is, that nexus does not send the "account" in the URL as the Docker Client do.
This seems to result in a Token that has no Access
 Redacted Login of the Docker Client
![image](https://github.com/sonatype/nexus-public/assets/10107699/08c10cb1-4f49-46d9-a703-ec70ecbd8f0c)
Redacted Response of the Docker Client
![image](https://github.com/sonatype/nexus-public/assets/10107699/6135e01a-c3c1-4786-990f-f73b9b727872)
Redacted Login of Nexus:
![image](https://github.com/sonatype/nexus-public/assets/10107699/9e43ee3f-69f4-4961-b698-20e6f59dee97)
Redacted Response of Nexus:
![image](https://github.com/sonatype/nexus-public/assets/10107699/65aa429b-7153-44dd-9490-b8e4cd1aa767)

Redacted JWT Token (left Docker right nexus)
![image](https://github.com/sonatype/nexus-public/assets/10107699/1b890674-a38e-4fdb-b90c-f71fc778d15e)
As you can see here the entire access array is empty for nexus.
* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?
Nexus/3.64.0-04 (OSS; Linux; 6.1.0-18-amd64; amd64; 1.8.0_402)
* Anything else?

**Comment by nblair** [comment]
Thanks for opening an issue @marcohald. I'm not 100% positive we fully support proxying Azure Container Registry at present, as evidenced by the detailed investigation. We'll have to review what's possible and report back; it may need to be an enhancement request.

**Comment by marcohald** [comment]
Sorry for opening this Issue.
I tried to add the account parameter with a intercepting proxy and then recognized that i still get no valid token.
I rechecked everything and spotted a Typo in the Image Name.
Sonatype Nexus seems to be fully compatible to Azure Container Registry.
