### ISSUE TITLE
How to delete Docker Manifests not assigned to images using Nexus API

### ISSUE THREAD

**Issue by Rumpeltilzky** [sonatype/nexus-public#403]
**VERSION**

Sonatype Nexus RepositoryOSS 3.68.1-02

**CASE**

Everyday we upload new images to our Nexus repository with the tag 'latest'. It means  that the previous manifest is left without an associated tag. We would like to delete those manifests which are not associated to the tags using only API requests.

**QUESTION**

Is there a recommended approach or specific API endpoint that can help us identify and delete these manifests efficiently?

Thanks in advance!

**Comment by yakirm-cr** [comment]
According to the [documentation](https://help.sonatype.com/en/tasks.html) this can be achieved by creating two tasks via Nexus settings &rarr; Tasks:
1. Docker - Delete unused manifests and images:
  ![image](https://github.com/sonatype/nexus-public/assets/86773995/bd4fe485-1b81-4d5b-81b1-84c0e6f71013)
1. Admin - Compact blob store:
  ![image](https://github.com/sonatype/nexus-public/assets/86773995/28444032-4a20-4c27-90e7-49cbf91554de)

You need to make sure that 1<sup>st</sup> task above is executed/scheduled before the 2<sup>nd</sup> task
Note that once the blob store is compacted, content marked as soft deleted will be completely removed.

**Comment by nblair** [comment]
Thanks @yakirm-cr - that's spot on. @Rumpeltilzky does that answer your question?

**Comment by Rumpeltilzky** [comment]
Sorry for my late reply! Thanks @yakirm-cr !! It worked as intended

**Comment by Rocket4220** [comment]
https://github.com/myscale/ChatData.git

**Comment by Rocket4220** [comment]
[c-main (2).zip](https://github.com/user-attachments/files/16138169/c-main.2.zip)

**Comment by Rocket4220** [comment]
[](url)htx
