### ISSUE TITLE
valid APKs with APK signatures in addition to JAR sigs cause crash in review: Unexpected record signature: 0X0

### ISSUE THREAD

**Issue by eighthave** [sonatype/nexus-public#406]
# What problem are you trying to solve?

I am trying to publish Android APK files with a valid signature (APKv2+) to Maven Central OSSRH.  This works fine with APKs that are only signed by JAR Signatures.  APKs now also have an additional signature (APKv2+ signatures).  When these signatures are present, it is not possible to include an APK in Maven Central OSSRH due to a crash in Nexus Repository Manager.

To reproduce:
* upload [_bundle.zip_](https://github.com/user-attachments/files/15759807/bundle.zip) to oss.sonatype.org to a "Staging Repository" (you might need to change the Group ID in the POM included in the ZIP).
* Check the "Activity" tab and see the failure: "Failed: Archives must not contain insecure paths" and "Unable to process file /org/fdroid/test-services/1.1.0/test-services-1.1.0.apk: Unexpected record signature: 0X0"

![Screenshot from 2024-06-10 11-29-14](https://github.com/sonatype/nexus-public/assets/143465/7a4c5930-3f91-4611-aaa5-97c06fe87487)

## Do you have a workaround you are using at present?

I could not find a workaround, except for publishing APKs that only work up until Android 10 (released 2019).  So functionality is currently blocked by this bug.  The closest I could come up with is to put the APK into another ZIP with its own POM, which then means installing it will require hacky scripts.

## What feature or behavior is this required for?

There are a number of use cases for APKs in Maven repos.  For example, some test libraries need to install an APK in order to function.  Google publishes this kind of APK in their official Maven repo:

* https://maven.google.com/web/index.html?q=test-ser#androidx.test.services:test-services:1.1.0
* https://dl.google.com/android/maven2/androidx/test/services/test-services/1.1.0/test-services-1.1.0.apk

## How could we solve this issue? (Not knowing is okay!)

One proven approach is to use `ZipFile` instead of `ZipArchiveInputStream` for parsing APKs.  APKs are basically signed JAR files with some small differences.  They then introduced a new [signing scheme](https://source.android.com/docs/security/features/apksigning/v2) in addition to JAR signatures.

Another approach would be to fix `ZipArchiveInputStream` to stop crashing on APK signatures:
https://issues.apache.org/jira/browse/COMPRESS-562

## Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

Maven Central OSSRH https://s01.oss.sonatype.org

**Comment by nblair** [comment]
Hi @eighthave - thanks for opening an issue. Your request here is specifically about publishing to Maven Central (OSSRH) and not about Sonatype Nexus Repository 3.

Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.

**Comment by eighthave** [comment]
For anyone else hitting this issue, it was solved by emailing support.  They changed some settings on our namespace, then it worked.
