### ISSUE TITLE
docker proxy anonymous access 401

### ISSUE THREAD

**Issue by Rabbit-st** [sonatype/nexus-public#410]
* What problem are you trying to solve?
docker proxy anonymous access 401

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

nexus3 version: `3.69.0-02`
system: `docker run sonatype/nexus3`
* Anything else?

1. anonymous rule privileges: `nx-repository-view-docker-*-*`
2. Realms has also been configured `Docker Bearer Token Realm`
3. docker proxy checked `Allow anonymous docker pull ( Docker Bearer Token Realm required )`

Anonymous access or prompt 401, what else do I need to configure?

**Comment by Rabbit-st** [comment]
The same configuration is available in version 3.38.1. Is there anything new in version 3.69?

**Comment by nblair** [comment]
Hi @Rabbit-st thanks for opening an issue. Configuring anonymous access with docker repositories can be tricky, as docker clients do some pretty unexpected things. 
Can you confirm you've followed the steps listed in https://help.sonatype.com/en/docker-authentication.html?

**Comment by Rabbit-st** [comment]
> 你好@Rabbit-st感谢您提出问题。使用 docker 存储库配置匿名访问可能很棘手，因为 docker 客户端会做一些非常出乎意料的事情。您能否确认您已按照https://help.sonatype.com/en/docker-authentication.html 中列出的步骤进行操作？[](https://help.sonatype.com/en/docker-authentication.html)

Yes, I followed the steps in the provided documentation to configure anonymous access, but it still doesn't work with version 3.69.0. However, anonymous access works with version 3.38.1.

**Comment by Rabbit-st** [comment]
Sorry, after reinstalling Nexus 3, anonymous access is now working.
