### ISSUE TITLE
Maven Cleanup Policy by Unused number days removed packages

### ISSUE THREAD

**Issue by marverix** [sonatype/nexus-public#413]
## What problem are you trying to solve?

I'm Using Nexus OSS 3.68.1. We have 2 maven hosted repositories and 1 group. We have defined a cleanup policy "Component Usage" to "60 days". Today after coming to work we discovered that during weekend all CI builds failed because of missing Gradle plugins (our own plugins stored in Nexus maven repository).

The folder strucutre existes, together with pom files and checksums, but what where missing were jar and xml (index) files. That was the pattern everywhere.

No one were removing those packages. We had no breach. Only thing working were Cleanup Policy. This is my only curprit. I don't know how to proof/debunk this.

Those plugins were downloaded 40-60 times per day, as we were using them for CI pipelines. Each pipeline is started on ephemeral runners, so each on each run, the plugins are fetched again.

Thus, I don't know "Component Usage" us working when using maven Proxy type and how Gradle Cache Server?

## Do you have a workaround you are using at present?

I needed to go 1 by 1 and re-publish all our Gradle plugins.

## What feature or behavior is this required for?

Cleanup Policy "Component Usage" should work as expected.

## How could we solve this issue? (Not knowing is okay!)

Please help me verify/debunk this theory. Or check on your side that it's working correctly. I don't even know how to start veryfing this issue.

## Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

Nexus OSS 3.68.1
Run on Kubernetes Cluster

**Comment by mrprescott** [comment]
@marverix Cleanup sees extensive use, I don't suspect a cleanup bug given what you've described. The cleanup task produces logs that describe what it's deleting, have a look at those. (In fact, scan all of the Repository logs for the names of components that are missing to see if they show up anywhere. Task logs, request logs, audit log, etc.)
