### ISSUE TITLE
Terraform registry support

### ISSUE THREAD

**Issue by dave-pl** [sonatype/nexus-public#415]
Hi, we use Nexus and we would like to use it for storing Terraform modules, so use it as a Terraform registry for modules. Currently, I don't see it is possible but as I know it was on your radar https://github.com/sonatype/nexus-public/issues/120
I didn't find a public roadmap or anything where I could find information on this feature. 
Do you plan to implement it? If yes, where can I track it? Our team wants to know when we can start using it :) 
Thanks!

Best,
Iaroslav

**Comment by mrprescott** [comment]
Thanks for filing this, @dave-pl. We don't have a public roadmap, but this helps us with our prioritization decisions when we do our periodic roadmap planning.
