### ISSUE TITLE
How to download a p2 repo to local?

### ISSUE THREAD

**Issue by Orangewithsugar** [sonatype/nexus-public#433]
Hello Nexus Team~
I want to download from nexus server , not import in a IDE , Just download the files, but I don't know how.
ForExample, i want to download this whole dir and nested files , but when i use wget it shows code 400
![image](https://github.com/sonatype/nexus-public/assets/88647663/554a08b6-887a-4468-853d-e01ce31ee8de)

Best Regards.

**Comment by mrprescott** [comment]
In some situations, the structure of the browse nodes doesn't map 1:1 to "directories" that you access via HTTP. What I recommend is that you find the URL of the repository itself, and navigate in from there.
