### ISSUE TITLE
Bower Support / H2

### ISSUE THREAD

**Issue by kmoens** [sonatype/nexus-public#447]
In our organisation we still have some legacy code which relies on Bower. For this purpose we make use of the Nexus 3 repository.

Sadly speaking, it appears that the Bower support is dropped as soon as we need the database migration, which drops support for OrientDB.

I agree that Bower is legacy, it is deprecated by the author already some time ago. However can we still get a version of Nexus 3 which supports Bower with H2?

Or if not, would it be possible to donate the code towards the community, so that the community can pick this up to create support for H2 / Postgres?

**Comment by Blacktiger** [comment]
I should note that 3.70.x will continue to get patches until Orient is entirely sunset so you don't _have_ to go to 3.71+. Obviously you'll miss out on any new features we develop.

**Comment by mrprescott** [comment]
@kmoens we are unlikely to ever build support for Bower at this stage of the game, but we will take your suggestion to heart as we think about "next best thing" options.
