### ISSUE TITLE
Nexus repository Upgrade path documentation is not up to date

### ISSUE THREAD

**Issue by dtronche** [sonatype/nexus-public#450]
When I search for Nexus repository upgrade path, I was sent to the page:
https://help.sonatype.com/en/supported-nexus-repository-manager-upgrade-paths.html

This page does not mention 3.71 breaking changes. It should mention that 3.70 is a mandatory upgrade release and the stop of support for Java and OrientDB

**Comment by lisadurant** [comment]
Thanks for this, @dtronche. I've added a line for this to our upgrade paths table to cross-ref the 3.71 upgrade paths doc & mention the breaking changes. You'll see it in our next routine publish.
