### ISSUE TITLE
New Project - Publish tk.milkthedev.consolemanager to Maven central

### ISSUE THREAD

**Issue by SpigotRCE** [sonatype/nexus-public#453]
Hi Team,

CosnoleManager is a light-weight library that mainly manages the console inputs for the user. I want to publish the library to maven central with OSSRH.

tk.milkthedev.consolemanager
ConsoleManager
1.0-SNAPSHOT

Github URL - https://github.com/SpigotRCE/ConsoleManager

Thanks,
SpigotRCE

**Comment by nblair** [comment]
Hi @SpigotRCE this issue tracker is not the right place to get the help you are looking for.

This issue tracker is specifically for deployments of Nexus Repository OSS.
Per (https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/):

[Registration and Namespace Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#registration-and-namespace-requests)
Users new to publishing via Maven Central will need to register via central.sonatype.com.

[Support Requests](https://central.sonatype.org/news/20240109_issues_sonatype_org_deprecation/#support-requests)
All other support requests will go through our [central-support@sonatype.com](mailto:central-support@sonatype.com) email.
