### ISSUE TITLE
I cannot find a clear way to reopen the H2 database after Linux server shutdown

### ISSUE THREAD

**Issue by yasser583** [sonatype/nexus-public#455]
I'm working with Nexus 3.71.0 on a server and it was shutdown without gracefully stopping Nexus. As a result, the H2 database got closed and I'm not able to make it work again. Here's a part of the log:

Error querying database.  Cause: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-224]
The error may exist in org/sonatype/nexus/internal/node/datastore/NodeIdDAO.xml
The error may involve defaultParameterMap
The error occurred while setting parameters
SQL: SELECT node_id FROM node_id WHERE id = 1;

Please your help.

**Comment by Blacktiger** [comment]
Perhaps try the H2 Recover Tool http://h2database.com/html/advanced.html#using_recover_tool ?

**Comment by yasser583** [comment]
Thank you @Blacktiger

**Comment by BhaskarraoP** [comment]
Hello @yasser583 

Could you please help me with how to gracefully stop Nexus using command-line instructions? 

Thank you!
