### ISSUE TITLE
OrientDB to H2 upgrade - Occurring schema versions that are not supported

### ISSUE THREAD

**Issue by GioMac** [sonatype/nexus-public#465]
nexus version: 3.70.1-02
nexus-db-migrator-3.70.1-03.jar

java -version
openjdk version "11.0.24" 2024-07-16 LTS
OpenJDK Runtime Environment (Red_Hat-11.0.24.0.8-2) (build 11.0.24+8-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-11.0.24.0.8-2) (build 11.0.24+8-LTS, mixed mode, sharing)

Migration fails:

15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - Migration job finished at Mon Sep 02 15:49:21 UTC 2024
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - Migration job took 29 seconds to execute
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - 0 records were processed
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - 0 records were filtered
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - 0 records were skipped
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - 0 records were migrated
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - ------------------------------------------------------------
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - Migration job finished with status FAILED.
15:49:21 [main] INFO  c.s.n.d.m.l.ProvidingJobInfoListener - Detailed message: com.sonatype.nexus.db.migrator.exception.WrongSchemaVersionException: Occurring schema versions that are not supported:
Upgrade ModelVersions{config='1.10', security='1.4', component='1.16', healthCheck='1.1', userToken='1.2', tags='1.1'}
Supported schema versions:
Upgrade ModelVersions{config='1.10', security='1.4', component='1.16', healthCheck='1.1', userToken='1.5', tags='1.1'}
Your OrientDB schemas are not supported by the current migrator version. Please update your Nexus Repository to the 3.70.1 version and use latest migrator version.

No messages in nexus log regarding old schema or upgrade failure.

**Comment by chkpnt** [comment]
You might have enabled/evaluated Pro-Features in the past, see https://github.com/sonatype/nexus-public/issues/451#issuecomment-2324866760.

**Comment by GioMac** [comment]
@chkpnt thank you
yes, that's the reason, checked solution - worked like a charm.
should I close this ticket or should we keep it for more attention as linked case's major subject is different?

**Comment by mrprescott** [comment]
Thanks for that insight, @chkpnt ! @GioMac Let's close this out for now to keep the board tidy. Thanks for circling back to report that the issue was solved.
