### ISSUE TITLE
nexus 3.70.2-01+ silently not starting with java 17+, no log entries/messages

### ISSUE THREAD

**Issue by muelli01** [sonatype/nexus-public#469]
I am trying to raise the java version from 8 to 17 on a Nexus server running v.3.70.2 (migrated to H2 DB).
I checked bin/nexus.vmoptions and uncommented the required lines as required in the file to run with java 9+ (and fixed some missing = apparently).
I installed java 17 and removed 8, "java --version" reports the correct version, but a "nexus start" just reports that nexus has been started. 
However now java process is spawned, no log entries are created. Just a silent fail.

When I roll back to java 8 and revert changed to nexus.vmoptions, it starts as usual.

For testing purposes I tried running nexus 3.72.0-04 but this version also just silently fails with java 17

**Comment by andreasmaennle** [comment]
I had a quite similar issue, which was caused by a 5 digit version number of java (17.0.11.0.101 - Azulu Zulu).
When using a 5 digit version number nexus fails at startup with the following message (you can only see this starting Nexus with ./bin/nexus run):
![image](https://github.com/user-attachments/assets/71eac27f-5b30-4c03-935b-4fa11da3fb4a)

I have fixed this issue by using a regular 3 digit version of java, or by setting the option -Dnexus.vmCheck=false in your nexus.vmoptions file.

**Comment by muelli01** [comment]
I re-did the whole process from scratch on a restored backup a couple of times. Several times it failed again silently (with the 5 digit version number: Red_Hat-17.0.11.0.9-3), however sometimes it succeeded without problems.
I cannot say what the differences have been, as - to me - everything was identical.

As the final test was successful, I will close this ticket as my nexus instance is now running on the latest version with java 17

**Comment by PhilSwiss** [comment]
@muelli01 could you shed some light on what you "fixed some missing = apparently" in bin/nexus.vmoptions, that would be super nice, thanks in advance.

**Comment by dhladky** [comment]
I am just trying to solve the same problem. The startup script picks Java 8 no matter what I have in JAVA_HOME. I added an echo to the startup script and it says: 

app_java_home=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/jre/bin/java

The same instance worked for years and now it does not. For version 3.77.2-02 it should be Java 17, which is the one I have in JAVA_HOME. 

% java -version               
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment Temurin-17.0.12+7 (build 17.0.12+7)
OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (build 17.0.12+7, mixed mode)

**Comment by dhladky** [comment]
Following workaround helped: 
before running ./nexus run using
export app_java_home=$JAVA_HOME
