### ISSUE TITLE
[Question] how to corretly setup docker Image Cleanup Rules? (Blobs not deleted)

### ISSUE THREAD

**Issue by MSandro** [sonatype/nexus-public#474]
Hi, Nexus is a great piece of software. But I have to deal with a problem on a regular basis.

We are using the sonatype/nexus3:3.70.2 Image for our Docker Image and Helm Chart Registry.
The need for storage is increasing and increasing. Although we have set a Cleanup-Rule to keep only the Docker images of the last 2 days. The storage requirement is around 300 GB. The images have an average size of 100 MB, as most of them are based on Apline.

We have many self-developments in ASP.NET. Our images use multiple layers. This should make it easy to delete blobs that are no longer needed.

How do you get it to automatically delete the blobs that are no longer referenced?

Thanks.

**Comment by mrprescott** [comment]
You may need to schedule the blob store compaction task, is that something you've done? By default, deleted blobs are _soft-deleted_ and their space isn't reclaimed immediately.
