### ISSUE TITLE
nexus3:3.72.0-java17-ubi image HIGH CVE vulnerabilities

### ISSUE THREAD

**Issue by irizzant** [sonatype/nexus-public#478]
Hello,
as you can see [here](https://artifacthub.io/packages/helm/stevehipwell-helm-charts-nexus3/nexus3?modal=security-report) there are 4 HIGH CVE in nexus3:3.72.0-java17-ubi image.
![immagine](https://github.com/user-attachments/assets/0739859e-c80f-4458-8fd3-9b7767cda90b)

They are all fixable

**Comment by mrprescott** [comment]
Thanks for posting this, @irizzant. These are on our radar.
