### ISSUE TITLE
Migration database orientdb to h2 problem with composer

### ISSUE THREAD

**Issue by bsnarski-CKPL** [sonatype/nexus-public#480]
I am using Nexus 3.70.2 with the nexus-repository-composer plugin. When performing a migration to the H2 database, the composer type is not recognized. The migration completes successfully for all types except composer. Is there a way to perform the migration while preserving all composer objects?
Has anyone else encountered this issue and knows how to perform a migration from OrientDB to H2 while preserving composer objects?

**Comment by mrprescott** [comment]
@bsnarski-CKPL Unfortunately, the community support for Composer doesn't cover the newer databases, so there's currently no path forward for Composer binaries. What some users are doing is maintaining an older instance, although that carries its own risks of course. We're reviewing the demand for official support for Composer to try to make this easier in the future.
