### ISSUE TITLE
Nexus MUST have H2 2.3.230 or later, it can crash otherwise

### ISSUE THREAD

**Issue by eliasbalasis** [sonatype/nexus-public#521]
* What problem are you trying to solve?

Nexus crashed while running due to a bug in H2 database driver.

>Invalid chunk id 0

see https://github.com/h2database/h2database/issues/4102

>This has crashed one of the most recent versions of Nexus, 3.72.0-04 while 3.74.0-05 which is the latest currently does not seem to be resolving the issue, probably because it does not carry H2 2.3.230+
> 3.72.0-04 was running without issues and it seems to have suffered from a catastrophic failure because of this.

* Do you have a workaround you are using at present?

No workaround

* What feature or behavior is this required for?

Nexus crashed while running due to a bug in H2 database driver.

* How could we solve this issue? (Not knowing is okay!)

Create a new release, with H2 driver 2.3.230 or later.

* Tell us about your Nexus Repository deployment: what version, operating system, and database are you using?

3.74.0-05 with H2 database

**Comment by BigBrokkokliMan** [comment]
We have the same problem with Nexus 3.74.0-05 since a few days. We always have to import the same database backup that is a few days old. After this wie execute the Task "Reconcile component database from blob store" for every repository. Please provide a new version of Nexus Repository Manager.

**Comment by dhs-rec** [comment]
BTW: Title says "2.**2**.230 or later"...

**Comment by dhs-rec** [comment]
As a workaround, I've replaced the H2 jar with the latest version (2.3.232) in our Nexus installation and it seems to be working fine so far since ~2 weeks.

**Comment by eliasbalasis** [comment]
> BTW: Title says "2.**2**.230 or later"...

It is 2.2.230 or later, indeed.

**Comment by dhs-rec** [comment]
Ah, sorry, was confused by the 2.3.xxx in the text. Of course, 2.**2**.230 fixes the problem, but the latest version is 2.**3**.232 (which is the one that also works for me).

**Comment by dhs-rec** [comment]
Damn, this is also wrong. There is no 2.**2**.230, according to their [changelog](https://www.h2database.com/html/changelog.html)...

**Comment by nblair** [comment]
Thanks everyone for your patience: today's release, [3.75.0](https://help.sonatype.com/en/sonatype-nexus-repository-3-75-0-release-notes.html), includes version 2.3.232 of the H2 database driver.
