### ISSUE TITLE
There are two different repositories under group, both with the same package name and version, which cannot be returned in group member order

### ISSUE THREAD

**Issue by linliaoy** [sonatype/nexus-public#528]
There are two different repositories under group, two different repositories have the same package name and version, but the upload time is different, but under the group url you see the latest version time displayed in maven-metadata.xml。
1.2-20241126.031054-1   and 1.2-20241126.030935-1 are packages pushed from different repositories, The maven-metadata.xml below 1.2-SNAPSHOT will write the latest push version, how can I match the group member order and return it
![image](https://github.com/user-attachments/assets/0d155a95-4dd6-4fc0-849f-4adbc1bd2663)

**Comment by linliaoy** [comment]
![image](https://github.com/user-attachments/assets/ba995810-27f3-4ecf-bc19-fbbefcd408fb)

**Comment by linliaoy** [comment]
I tested it with  nexus oss 3.74.0-05   and  2.14.15-01 , and it was the same

**Comment by linliaoy** [comment]
[nexus2 doc](https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/2/Sonatype%20Nexus%20Repository%202%20Help.pdf)

<img width="734" alt="image" src="https://github.com/user-attachments/assets/bbe7c104-4177-4dfc-8b38-0a2cec379652">

**Comment by yakirm-cr** [comment]
Interesting!

Basically, even though those artifacts are under the same SNAPSHOT version (`1.2-SNAPSHOT`), they are considered as two different versions (due to the different timestamps) and therefore, Nexus considers them as two separate entries and lists them both (the `maven-metadata.xml` considers the one with the latest timestamp as the latest `1.2-SNAPSHOT`, which is the expected behavior of Maven).

I am not really sure whether it is a bug or a feature. :confused:

**Comment by mrprescott** [comment]
This is the intended behavior. As @yakirm-cr points out, Nexus (like maven) treats each snapshot as a different version.

Group repositories in Nexus merge the metadata of their members to come up with a consolidated list, and it's ultimately the maven client that decides what you download when you ask for 1.2-SNAPSHOT. Maven downloads the consolidated list and picks the latest.

Can I ask why you're publishing snapshots for the same component to two different repositories? If you always want the latest snapshot from member repository A, why is member repository B in the group?

**Comment by linliaoy** [comment]
> This is the intended behavior. As @yakirm-cr points out, Nexus (like maven) treats each snapshot as a different version.
> 
> Group repositories in Nexus merge the metadata of their members to come up with a consolidated list, and it's ultimately the maven client that decides what you download when you ask for 1.2-SNAPSHOT. Maven downloads the consolidated list and picks the latest.
> 
> Can I ask why you're publishing snapshots for the same component to two different repositories? If you always want the latest snapshot from member repository A, why is member repository B in the group?

Our project A is in repositories A, while Project B uses repositories B. Project B will also refer to some jar packages of repositories A, and Project B will also have some special requirements and submit A copy of the modified code in repositories A to repositories B, because many project references do not change the version number

**Comment by linliaoy** [comment]
> Interesting!
> 
> Basically, even though those artifacts are under the same SNAPSHOT version (`1.2-SNAPSHOT`), they are considered as two different versions (due to the different timestamps) and therefore, Nexus considers them as two separate entries and lists them both (the `maven-metadata.xml` considers the one with the latest timestamp as the latest `1.2-SNAPSHOT`, which is the expected behavior of Maven).
> 
> I am not really sure whether it is a bug or a feature. 😕

When I was packaging gradle, gradle did not follow the order of "Ordered Group Repositories" in the document, but directly used the maven-metadata.xml file. I wonder if you could help me explain how gradle uses nexus "Ordered Group Repositories"

**Comment by linliaoy** [comment]
[Explaining-slow-performance-resolving-artifacts-in-Nexus-Repository-2](https://support.sonatype.com/hc/en-us/articles/213465198-Explaining-slow-performance-resolving-artifacts-in-Nexus-Repository-2)
It is documented that accessing maven-metadata.xml directly will aggregate the same packages and versions, but how can I use "Ordered Group Repositories" in gradle to return the first match

**Comment by mrprescott** [comment]
> Our project A is in repositories A, while Project B uses repositories B. Project B will also refer to some jar packages of repositories A, and Project B will also have some special requirements and submit A copy of the modified code in repositories A to repositories B, because many project references do not change the version number

This sounds like asking for difficulties. If you're going to take two components that aren't substitutes, give them the same name and then make both available in the same place to consumers who care which one they get, you're working against yourself here.

Best recommendation is to give the modified components different names, or somehow refactor the functionality so it can be altered without tweaking the binary.

**Comment by linliaoy** [comment]
> > Our project A is in repositories A, while Project B uses repositories B. Project B will also refer to some jar packages of repositories A, and Project B will also have some special requirements and submit A copy of the modified code in repositories A to repositories B, because many project references do not change the version number
> 
> This sounds like asking for difficulties. If you're going to take two components that aren't substitutes, give them the same name and then make both available in the same place to consumers who care which one they get, you're working against yourself here.
> 
> Best recommendation is to give the modified components different names, or somehow refactor the functionality so it can be altered without tweaking the binary.

Okay, well, the nexus documentation says you can "Ordered Group Repositories," but I still don't know in what order

**Comment by mrprescott** [comment]
> Okay, well, the nexus documentation says you can "Ordered Group Repositories," but I still don't know in what order

If you have a maven group repository with members A and B, it will serve files by checking A first then B. The maven metadata file will list all of the snapshots.

Gradle will download the metadata and look for the most recent snapshot version/timestamp, and then it will request that specific file from the group. If member A doesn't have that version, the group will serve it from member B.

**Comment by linliaoy** [comment]
> > Okay, well, the nexus documentation says you can "Ordered Group Repositories," but I still don't know in what order
> 
> If you have a maven group repository with members A and B, it will serve files by checking A first then B. The maven metadata file will list all of the snapshots.
> 
> Gradle will download the metadata and look for the most recent snapshot version/timestamp, and then it will request that specific file from the group. If member A doesn't have that version, the group will serve it from member B.

Thank you. I get it
