### ISSUE TITLE
Can't add or edit s3 blobstore on s3 providers who has no /?lifecycle support

### ISSUE THREAD

**Issue by MaxVorobyev** [sonatype/nexus-public#539]
Can't add or edit s3 blobstore on s3 providers who has no /?lifecycle support (like “Seaweedfs”)
On java 1.8 and Nexus Repository Version 3.70.1 the problem is absent.
```
curl -X 'POST' \
'https://repo.url/service/rest/v1/blobstores/s3' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-H 'NX-ANTI-CSRF-TOKEN: 0.9579054405939501' \
-H 'X-Nexus-UI: true' \
-d '{
"name": "blob-name",
"softQuota": null,
"bucketConfiguration": {
"bucket": {
"region": "us-east-1",
"name": "bucket-name",
"prefix": "",
"expiration": "-1"

},
"failoverBuckets": [],
"activeRegion": "us-east-1",
"bucketSecurity": {
"accessKeyId": "dummy-user",
"secretAccessKey": "dummy-password"
},
"advancedBucketConnection": {
"endpoint": "https://s3.url/",
"forcePathStyle": true
}
}
}'
```

```
Error: response status is 400
ValidationErrorXO{id='*', message='Unable to initialize blob store bucket: nexus-kbtt-pypi-local, Cause: Cannot invoke "String.equals(Object)" because the return value of "com.amazonaws.services.s3.model.BucketLifecycleConfiguration$Rule.getId()" is null'}
```

Nexus Repository deployment:
Nexus Repository Version - OSS 3.75.1-01
OS - Ubuntu 24.04.1 LTS
Java - openjdk version "17.0.13" 2024-10-15

**Comment by mrprescott** [comment]
@MaxVorobyev Unfortunately, Nexus Repository isn't compatible with any old S3-alike implementation, for reasons exactly like this. As we evolve and improve our use over time, we won't necessarily notice when we cross the boundary between what a partially S3-compatible use supports and what it doesn't.
